PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS quotes (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, tag TEXT NOT NULL, quote TEXT NOT NULL, tagalog TEXT NOT NULL);
INSERT INTO quotes VALUES(1,'love','Forgiveness heals and empowers. ','Ang pagpapatawad ay nagpapagaling at nagbibigay lakas.');
INSERT INTO quotes VALUES(2,'love',replace('\nI release anger and embrace peace. ','\n',char(10)),'Binibitawan ko ang galit at tinatanggap ang kapayapaan.');
INSERT INTO quotes VALUES(3,'love',replace('\nI choose love over resentment. ','\n',char(10)),'Pinipili ko ang pag-ibig kaysa sa pagtatanim ng sama ng loob.');
INSERT INTO quotes VALUES(4,'love',replace('\nI forgive to set myself free. ','\n',char(10)),'Nagpapatawad ako upang palayain ang aking sarili.');
INSERT INTO quotes VALUES(5,'love',replace('\nI let go of grudges for my well-being. ','\n',char(10)),'Iniiwan ko ang mga hinanakit para sa aking kapakanan.');
INSERT INTO quotes VALUES(6,'love','Love will find its way to me when the time is right.','Ang pag-ibig ay darating sa akin kapag tamang panahon na.');
INSERT INTO quotes VALUES(7,'love',replace('\nI attract love effortlessly into my life.','\n',char(10)),'Madaling dumaan ang pag-ibig sa aking buhay.');
INSERT INTO quotes VALUES(8,'love',replace('\nI am open to receiving love in all its forms.','\n',char(10)),'Bukas ako sa pagtanggap ng pag-ibig sa lahat ng anyo.');
INSERT INTO quotes VALUES(9,'love',replace('\nLove flows to me abundantly and effortlessly.','\n',char(10)),'Ang pag-ibig ay dumadaloy sa akin nang sagana at walang kahirap-hirap.');
INSERT INTO quotes VALUES(10,'love',replace('\nI am worthy of love and it comes to me naturally.','\n',char(10)),'Karapat-dapat ako sa pag-ibig at ito''y dumarating sa akin nang natural.');
INSERT INTO quotes VALUES(11,'love','Love yourself wholeheartedly; you deserve all the love in the world!','Mahalin mo ang iyong sarili nang buong puso; karapat-dapat kang mahalin ng buong mundo!');
INSERT INTO quotes VALUES(12,'love',replace('  \nEmbrace self-love daily; it is the foundation of loving others deeply!','\n',char(10)),'Yakapin ang pagmamahal sa sarili araw-araw; ito ang pundasyon ng pagmamahal sa iba nang lubusan!');
INSERT INTO quotes VALUES(13,'love',replace('  \nNurture self-compassion; it will radiate towards everyone around you!','\n',char(10)),'Alagaan ang pagbibigay ng kalinga sa sarili; ito ay magrereplika sa lahat ng nasa paligid mo!');
INSERT INTO quotes VALUES(14,'love',replace('  \nCherish your uniqueness; it is the essence of your remarkable being!','\n',char(10)),'Pahalagahan ang iyong kakaibang pagkatao; ito ang essensya ng iyong kahanga-hangang pagkatao!');
INSERT INTO quotes VALUES(15,'love','Forgiveness heals my heart and liberates my soul. ','Ang pagpapatawad ay nagpapagaling sa aking puso at pinalalaya ang aking kaluluwa.');
INSERT INTO quotes VALUES(16,'love','Forgiveness brings me peace and sets me free. ','Ang pagpapatawad ay nagdadala ng kapayapaan sa akin at naglalaya sa akin.');
INSERT INTO quotes VALUES(17,'love','I choose forgiveness to cultivate self-giving love. ','Pinili ko ang pagpapatawad upang palaguin ang pagmamahal sa sarili.');
INSERT INTO quotes VALUES(18,'love','Forgiveness is my gift to myself and others. ','Ang pagpapatawad ay regalo ko sa sarili at sa iba.');
INSERT INTO quotes VALUES(19,'love','I release anger and embrace love through forgiveness. ','Binibitawan ko ang galit at inaakap ang pag-ibig sa pamamagitan ng pagpapatawad.');
INSERT INTO quotes VALUES(20,'love','Friendship blossoms into love effortlessly. ',replace(' Ang pagkakaibigan ay madaling lumalago patungo sa pag-ibig.\nLove is everlasting and transcends mere friendship. ','\n',char(10)));
INSERT INTO quotes VALUES(21,'love','You are capable of attracting love and friendship effortlessly. ',' Ikaw ay may kakayahang maakit ng pag-ibig at pagkakaibigan nang walang anumang pagod. ');
INSERT INTO quotes VALUES(22,'love',replace(' \nYou are deserving of genuine love and rare friendships. ','\n',char(10)),' Ikaw ay karapat-dapat sa tunay na pag-ibig at bihirang pagkakaibigan. ');
INSERT INTO quotes VALUES(23,'love',replace('\nYour life is filled with abundant love and precious friendships. ','\n',char(10)),' Ang iyong buhay ay puno ng masaganang pag-ibig at mahahalagang pagkakaibigan. ');
INSERT INTO quotes VALUES(24,'love',replace('\nYou radiate love and attract rare connections effortlessly. ','\n',char(10)),' Ikaw ay nagpapalabas ng pag-ibig at nahahatak ang bihirang mga koneksyon nang walang anumang pagod. ');
INSERT INTO quotes VALUES(25,'love',replace('\nYou are a magnet for love and rare, valuable friendships. ','\n',char(10)),' Ikaw ay isang magnet para sa pag-ibig at bihirang, mahalagang pagkakaibigan. ');
INSERT INTO quotes VALUES(26,'love','I am deserving of love and I choose to give it to myself. ',' Karapat-dapat ako sa pagmamahal at pinili kong ibigay ito sa sarili ko. ');
INSERT INTO quotes VALUES(27,'love',replace(' \nI radiate self-love and it attracts positivity into my life. ','\n',char(10)),' Aking pinararangalan ang pagmamahal sa sarili at ito ay umaakit ng positibong bagay sa aking buhay. ');
INSERT INTO quotes VALUES(28,'love',replace('\nMy self-love grows stronger each day, nurturing my soul. ','\n',char(10)),' Lumalakas ang pagmamahal ko sa sarili araw-araw, itinataguyod nito ang aking kaluluwa. ');
INSERT INTO quotes VALUES(29,'love',replace('\nLoving myself first allows me to love others authentically. ','\n',char(10)),' Ang pagmamahal sa sarili ay nagbibigay-daan sa akin upang mapagmahal nang tapat sa iba. ');
INSERT INTO quotes VALUES(30,'love',replace('\nI am a vessel of love, starting with myself. ','\n',char(10)),' Ako ay isang sisidlan ng pagmamahal, nagsisimula sa sarili. ');
INSERT INTO quotes VALUES(31,'love','You radiate love effortlessly. ',' Lumalabas nang natural ang pagmamahal mo.');
INSERT INTO quotes VALUES(32,'love',replace('\nLove flows to me effortlessly. ','\n',char(10)),' Ang pag-ibig ay dumadaloy sa akin nang walang kahirap-hirap.');
INSERT INTO quotes VALUES(33,'love',replace('\nI attract love effortlessly. ','\n',char(10)),' Nahihila ko ang pagmamahal nang walang kahirap-hirap.');
INSERT INTO quotes VALUES(34,'love',replace('\nLove finds me easily. ','\n',char(10)),' Madaling natatagpuan ako ng pag-ibig.');
INSERT INTO quotes VALUES(35,'love',replace('\nI am a magnet for love. ','\n',char(10)),' Ako ay isang imagnet para sa pag-ibig.');
INSERT INTO quotes VALUES(36,'love','Forgiveness heals my heart and sets me free. ','Ang pagpapatawad ay nagpapagaling sa puso ko at nagpapalaya sa akin.');
INSERT INTO quotes VALUES(37,'love','Forgiveness is a gift I give to myself. ','Ang pagpapatawad ay regalo na binibigay ko sa sarili ko.');
INSERT INTO quotes VALUES(38,'love','I release resentment and choose to love. ','Ako ay nagpapakawala ng sama ng loob at pinipili ang magmahal.');
INSERT INTO quotes VALUES(39,'love','Forgiveness empowers me to let go and heal. ','Ang pagpapatawad ay nagbibigay sa akin ng lakas na mag-let go at magpagaling.');
INSERT INTO quotes VALUES(40,'love',replace('\nForgiveness is a choice that nourishes my soul. ','\n',char(10)),'Ang pagpapatawad ay isang pagpili na pinalalakas ang aking kaluluwa.');
INSERT INTO quotes VALUES(41,'love','You are deserving of the love that finds you. ','Ikaw ay karapat-dapat sa pag-ibig na nagmumula.');
INSERT INTO quotes VALUES(42,'love',replace('\nLove is always searching for you. ','\n',char(10)),'Ang pag-ibig ay palaging naghahanap sa iyo.');
INSERT INTO quotes VALUES(43,'love',replace('\nYou are open to receiving the love meant for you. ','\n',char(10)),'Handa kang tanggapin ang pag-ibig na para sa iyo.');
INSERT INTO quotes VALUES(44,'love',replace('\nLove comes effortlessly into your life. ','\n',char(10)),'Ang pag-ibig ay dumarating nang walang anumang pagsisikap sa iyong buhay.');
INSERT INTO quotes VALUES(45,'love',replace('\nYou attract the love that is destined for you. ','\n',char(10)),'Ikaw ay bumabagay sa pag-ibig na nakalaan para sa iyo.');
INSERT INTO quotes VALUES(46,'love','You deserve love and kindness. ',' Nararapat kang mahalin at tratuhin nang mabuti.');
INSERT INTO quotes VALUES(47,'love',replace('\nSelf-love is essential for a fulfilling life. ','\n',char(10)),' Ang pagmamahal sa sarili ay mahalaga para sa masaganang buhay.');
INSERT INTO quotes VALUES(48,'love',replace('\nYou are worthy of your own love. ','\n',char(10)),' Ikaw ay karapat-dapat sa iyong sariling pagmamahal.');
INSERT INTO quotes VALUES(49,'love',replace('\nLoving yourself is a powerful act of self-care. ','\n',char(10)),' Ang pagmamahal sa sarili ay isang makapangyarihang aktong pangangalaga sa sarili.');
INSERT INTO quotes VALUES(50,'love',replace('\nBy loving yourself, you can better love others. ','\n',char(10)),' Sa pamamagitan ng pagmamahal sa sarili, mas magiging mahusay kang magmahal ng iba.');
INSERT INTO quotes VALUES(51,'peace','Share your smile with the world. ','Ibahagi ang iyong ngiti sa mundo.');
INSERT INTO quotes VALUES(52,'peace',replace('\nIt''s a symbol of friendship and peace. ','\n',char(10)),'Ito ay simbolo ng pagkakaibigan at kapayapaan.');
INSERT INTO quotes VALUES(53,'peace','Resolutely train yourself to attain peace.','Matiyagang magtren sa sarili upang makamit ang kapayapaan.');
INSERT INTO quotes VALUES(54,'peace','You bring peace with your words. ',' Ikaw ang nagdudulot ng kapayapaan sa iyong mga salita. ');
INSERT INTO quotes VALUES(55,'peace',replace(' \nYour words have the power to bring peace. ','\n',char(10)),' Ang iyong mga salita ay may kapangyarihan na magdala ng kapayapaan. ');
INSERT INTO quotes VALUES(56,'peace',replace('\nSpeak words that bring peace to others. ','\n',char(10)),' Magsalita ng mga salitang nagdudulot ng kapayapaan sa iba. ');
INSERT INTO quotes VALUES(57,'peace',replace('\nYour words hold the key to peace. ','\n',char(10)),' Ang iyong mga salita ang susi sa kapayapaan. ');
INSERT INTO quotes VALUES(58,'peace',replace('\nChoose peace in every word you speak. ','\n',char(10)),' Pumili ng kapayapaan sa bawat salita na iyong binibigkas. ');
INSERT INTO quotes VALUES(59,'peace','Share your smile with the world. ','Ibahagi ang iyong ngiti sa mundo.');
INSERT INTO quotes VALUES(60,'peace',replace('\nIt''s a symbol of friendship and peace. ','\n',char(10)),'Ito ay simbolo ng pagkakaibigan at kapayapaan.');
INSERT INTO quotes VALUES(61,'peace','Embrace peace in every word I speak',' Pagharian ang kapayapaan sa bawat salita na aking binitawan');
INSERT INTO quotes VALUES(62,'peace',replace('\nI choose words that bring harmony and understanding','\n',char(10)),' Piliin ang mga salitang nagdadala ng pagkakaunawaan at pagkakaisa');
INSERT INTO quotes VALUES(63,'peace',replace('\nMy words have the power to heal and comfort','\n',char(10)),' Ang aking mga salita ay may kapangyarihan na magpagaling at magbigay ng ginhawa');
INSERT INTO quotes VALUES(64,'peace',replace('\nI cultivate a language of kindness and empathy','\n',char(10)),' Ako ay nagtatanim ng wika ng kabaitan at pag-unawa');
INSERT INTO quotes VALUES(65,'peace',replace('\nMy voice carries the essence of tranquility','\n',char(10)),' Ang aking boses ay naglalaman ng kagandahang-loob');
INSERT INTO quotes VALUES(66,'peace','You attract peace by releasing resentful thoughts. ',' Natatamo ang kapayapaan sa pagpapakawala ng sama ng loob. ');
INSERT INTO quotes VALUES(67,'peace',replace(' \nPeace blossoms in a mind free of resentment. ','\n',char(10)),' Ang kapayapaan ay lumalago sa isipan na walang sama ng loob. ');
INSERT INTO quotes VALUES(68,'peace',replace(' \nLet go of resentful thoughts to embrace peace. ','\n',char(10)),' Ibitaw ang sama ng loob upang yakapin ang kapayapaan. ');
INSERT INTO quotes VALUES(69,'peace',replace(' \nResentment-free thoughts pave the way to peace. ','\n',char(10)),' Ang pagiging malaya sa sama ng loob ang nagbubukas ng landas tungo sa kapayapaan. ');
INSERT INTO quotes VALUES(70,'peace',replace(' \nEmbrace peace by freeing yourself from resentful thoughts. ','\n',char(10)),' Yakapin ang kapayapaan sa pamamagitan ng pagpapakawala sa sama ng loob. ');
INSERT INTO quotes VALUES(71,'peace','Resolutely train yourself to attain peace. ','Tapangang mag-aral upang makamit ang kapayapaan.');
INSERT INTO quotes VALUES(72,'peace',replace('\nBelieve in your strength to conquer challenges. ','\n',char(10)),'Maniwala sa iyong lakas upang malampasan ang mga hamon.');
INSERT INTO quotes VALUES(73,'peace',replace('\nRadiate positivity in every aspect of your life. ','\n',char(10)),'Ipamalas ang positibong pananaw sa bawat aspeto ng iyong buhay.');
INSERT INTO quotes VALUES(74,'peace',replace('\nEmbrace your journey towards self-discovery. ','\n',char(10)),'Yakapin ang iyong paglalakbay tungo sa pagkilala sa sarili.');
INSERT INTO quotes VALUES(75,'peace',replace('\nYou are deserving of love and happiness. ','\n',char(10)),'Karapat-dapat ka sa pagmamahal at kaligayahan.');
INSERT INTO quotes VALUES(76,'peace','Peace arises from understanding, not from force.','Ang kapayapaan ay nagmumula sa pag-unawa, hindi sa puwersa.');
INSERT INTO quotes VALUES(77,'peace',replace('\nStrength lies in empathy, not in aggression.','\n',char(10)),'Ang lakas ay nasa pagmamalasakit, hindi sa pag-atake.');
INSERT INTO quotes VALUES(78,'peace',replace('\nEmpathy conquers conflict with understanding.','\n',char(10)),'Ang pagmamalasakit ang nagtutulak sa pagkakaisa.');
INSERT INTO quotes VALUES(79,'peace',replace('\nUnderstanding breeds harmony, not dominance.','\n',char(10)),'Ang pag-unawa ang nagbubunga ng pagkakaisa, hindi ng pang-aapi.');
INSERT INTO quotes VALUES(80,'peace',replace('\nCompassion fosters lasting peace, not control.','\n',char(10)),'Ang pagmamalasakit ang nagtataguyod ng pangmatagalan kapayapaan, hindi ng kontrol.');
INSERT INTO quotes VALUES(81,'joy','I release resentment and make space for joy.',replace('Pinalalaya ko ang hinanakit at binibigyang-daan ang kasiyahan.\n\nI choose to let go of bitterness and welcome happiness.','\n',char(10)));
INSERT INTO quotes VALUES(82,'joy','Embrace the irony in life''s twists and turns. ','Tanggapin ang ironya sa mga kaganapan ng buhay.');
INSERT INTO quotes VALUES(83,'joy',replace('\nReflect on the joy found in wisdom''s depths. ','\n',char(10)),'Magbalik-tanaw sa kasiyahang hatid ng karunungan.');
INSERT INTO quotes VALUES(84,'joy',replace('\nFind gaiety in the dance of life''s contradictions. ','\n',char(10)),'Hanapin ang kasiyahan sa sayaw ng mga kontradiksyon ng buhay.');
INSERT INTO quotes VALUES(85,'joy',replace('\nWisdom brings joy, even in life''s ironies. ','\n',char(10)),'Ang karunungan ay nagdadala ng kasiyahan, kahit sa mga ironya ng buhay.');
INSERT INTO quotes VALUES(86,'joy',replace('\nLet wisdom be your guide to finding joy in irony. ','\n',char(10)),'Pahintulutan ang karunungan na maging gabay sa paghahanap ng kasiyahan sa ironya.');
INSERT INTO quotes VALUES(87,'joy','Rejoicing in our joy attracts true friends. ','Ang pagdiriwang sa ating kasiyahan ay nagdudulot ng tunay na mga kaibigan.');
INSERT INTO quotes VALUES(88,'joy',replace('  \nEmbracing joy nurtures genuine connections. ','\n',char(10)),'Ang pagnanais ng kasiyahan ay nagpapalago ng tunay na ugnayan.');
INSERT INTO quotes VALUES(89,'joy',replace('  \nCelebrating each other''s happiness fosters friendship. ','\n',char(10)),'Ang pagsasaya sa kasiyahan ng isa''t isa ay nagtataguyod ng pagkakaibigan.');
INSERT INTO quotes VALUES(90,'joy',replace('  \nChoosing joy over suffering cultivates companionship. ','\n',char(10)),'Ang pagpili ng kasiyahan kaysa sa pagdurusa ay nagpapalago ng pakikipagkaibigan.');
INSERT INTO quotes VALUES(91,'joy',replace('  \nFinding joy in others creates lasting bonds. ','\n',char(10)),'Ang paghahanap ng kasiyahan sa iba ay lumilikha ng matibay na ugnayan.');
INSERT INTO quotes VALUES(92,'family','You are a cherished gift to your family. ','Ikaw ay isang pinahahalagahang regalo sa iyong pamilya.');
INSERT INTO quotes VALUES(93,'family',replace('\nYour family is a precious gift in your life. ','\n',char(10)),'Ang iyong pamilya ay isang mahalagang regalo sa iyong buhay.');
INSERT INTO quotes VALUES(94,'family',replace('\nYou bring love and joy to your family. ','\n',char(10)),'Ikaw ay nagdudulot ng pagmamahal at kasiyahan sa iyong pamilya.');
INSERT INTO quotes VALUES(95,'family',replace('\nYour family is a blessing from God. ','\n',char(10)),'Ang iyong pamilya ay isang biyaya mula sa Diyos.');
INSERT INTO quotes VALUES(96,'family',replace('\nYou and your family are meant for each other. ','\n',char(10)),'Kayo at ang inyong pamilya ay itinadhana para sa isa''t isa.');
INSERT INTO quotes VALUES(97,'family','Live humbly and appreciate simplicity every day. ','Mabuhay nang payak at pahalagahan ang simpleng buhay araw-araw.');
INSERT INTO quotes VALUES(98,'family',replace('\nBe kind and generous in resolving conflicts. ','\n',char(10)),'Maging mabait at maginoo sa paglutas ng hidwaan.');
INSERT INTO quotes VALUES(99,'family',replace('\nLead without the need for excessive control. ','\n',char(10)),'Pamunuan nang hindi umaasa sa sobrang kontrol.');
INSERT INTO quotes VALUES(100,'family',replace('\nDo what brings you joy in your daily tasks. ','\n',char(10)),'Gawin ang mga bagay na nagbibigay sa iyo ng kasiyahan araw-araw.');
INSERT INTO quotes VALUES(101,'family',replace('\nBe fully present in moments with your loved ones. ','\n',char(10)),'Maging lubos na naroroon sa mga sandali kasama ang iyong mga mahal sa buhay.');
INSERT INTO quotes VALUES(102,'family','I embrace the brotherhood and camaraderie in rock music. ',' Tinatanggap ko ang pagkakaisa at pakikipagkaibigan sa musikang rock. ');
INSERT INTO quotes VALUES(103,'family',replace(' \nMy love for rock music brings me a sense of belonging. ','\n',char(10)),' Ang pagmamahal ko sa musikang rock ay nagdudulot sa akin ng pakiramdam ng pag-aangkin. ');
INSERT INTO quotes VALUES(104,'family',replace(' \nI appreciate the unity and support within the rock community. ','\n',char(10)),' Pinahahalagahan ko ang pagkakaisa at suporta sa loob ng komunidad ng rock. ');
INSERT INTO quotes VALUES(105,'family',replace(' \nRock music reminds me of the importance of genuine connections. ','\n',char(10)),' Ang musikang rock ay nagpapaalala sa akin sa kahalagahan ng tunay na ugnayan. ');
INSERT INTO quotes VALUES(106,'family',replace(' \nI celebrate the spirit of friendship and kinship in rock and roll. ','\n',char(10)),' Pinagdiriwang ko ang espiritu ng pagkakaibigan at pagiging magkakapamilya sa rock and roll. ');
INSERT INTO quotes VALUES(107,'family','You are capable of achieving anything you set your mind to.','Kayang-kaya mong makamit ang anuman sa iyong minimithi.');
INSERT INTO quotes VALUES(108,'family',replace('\nYou radiate positivity and attract good things into your life.','\n',char(10)),'Ikaw ay nagpapakalat ng positibong enerhiya at bumabagay ng magagandang bagay sa iyong buhay.');
INSERT INTO quotes VALUES(109,'family',replace('\nYou are worthy of love and respect from yourself and others.','\n',char(10)),'Karapat-dapat kang mahalin at galangin ng iyong sarili at ng iba.');
INSERT INTO quotes VALUES(110,'family',replace('\nYou are a powerful creator of your own reality.','\n',char(10)),'Ikaw ay isang makapangyarihang lumikha ng iyong sariling realidad.');
INSERT INTO quotes VALUES(111,'family',replace('\nYou deserve all the success and happiness that come your way.','\n',char(10)),'Karapat-dapat kang magtagumpay at maging masaya sa lahat ng iyong nararating.');
INSERT INTO quotes VALUES(112,'family','I am loyal and trustworthy in my friendships. ','Ako ay tapat at mapagkakatiwalaan sa aking mga kaibigan.');
INSERT INTO quotes VALUES(113,'family','I value the bond of friendship. ','Mahalaga sa akin ang ugnayan ng pagkakaibigan.');
INSERT INTO quotes VALUES(114,'family','I am a true friend who stands the test of character. ','Ako ay tunay na kaibigan na lumalampas sa pagsubok ng karakter.');
INSERT INTO quotes VALUES(115,'family','I cherish the connections that go beyond blood ties. ','Pinahahalagahan ko ang mga koneksyon na lampas sa dugong magkakapatid.');
INSERT INTO quotes VALUES(116,'family','I radiate loyalty to my chosen family of friends. ','Aking pinapakita ang tapat sa aking piniling pamilya ng mga kaibigan.');
INSERT INTO quotes VALUES(117,'effort','You effortlessly become quicker and stronger every day!','Madali kang maging mas mabilis at mas malakas araw-araw!');
INSERT INTO quotes VALUES(118,'effort','Effortlessness brings out your speed and strength.','Ang kawalan ng pagsisikap ay nagbibigay-buhay sa iyong bilis at lakas.');
INSERT INTO quotes VALUES(119,'effort','Your power and speed increase effortlessly!','Lumalakas at bumibilis ka nang walang anumang pagod!');
INSERT INTO quotes VALUES(120,'effort','Ease leads to quickness and strength.','Ang kadalian ay nagdudulot ng mabilisang pag-unlad ng lakas at bilis.');
INSERT INTO quotes VALUES(121,'effort','You are becoming stronger and faster effortlessly!','Ikaw ay lumalakas at bumibilis nang hindi pinipilit!');
INSERT INTO quotes VALUES(122,'effort','Consistent action fuels my growth and success.','Tuloy-tuloy na pagkilos ang nagpapalakas sa aking pag-unlad at tagumpay.');
INSERT INTO quotes VALUES(123,'effort',replace('\nMy potential expands as I persist in my efforts.','\n',char(10)),'Lumalawak ang aking potensyal habang patuloy akong nagpupursigi.');
INSERT INTO quotes VALUES(124,'effort',replace('\nI focus on progress over perfection in my journey.','\n',char(10)),'Nakatuon ako sa pag-unlad kaysa sa kahusayan sa aking paglalakbay.');
INSERT INTO quotes VALUES(125,'effort',replace('\nEvery small step I take brings me closer to my goals.','\n',char(10)),'Bawat maliit na hakbang na aking ginagawa ay naglalapit sa akin sa aking mga layunin.');
INSERT INTO quotes VALUES(126,'effort',replace('\nI am capable of achieving anything with consistent action.','\n',char(10)),'Kaya kong makamit ang anuman sa pamamagitan ng tuloy-tuloy na pagkilos.');
INSERT INTO quotes VALUES(127,'effort','You are capable of producing quality with your intelligent efforts. ',' Ikaw ay kayang magbigay ng kalidad sa pamamagitan ng iyong matalinong pagsisikap. ');
INSERT INTO quotes VALUES(128,'effort',replace(' \nYour efforts lead to intentional and remarkable outcomes. ','\n',char(10)),' Ang iyong mga pagsisikap ay nagdudulot ng may layunin at kahanga-hangang mga resulta. ');
INSERT INTO quotes VALUES(129,'effort',replace(' \nYour hard work manifests into exceptional quality. ','\n',char(10)),' Ang iyong masisipag na gawa ay nagsasalin sa kahanga-hangang kalidad. ');
INSERT INTO quotes VALUES(130,'effort',replace(' \nExcellence is a natural outcome of your thoughtful actions. ','\n',char(10)),' Ang kahusayan ay likas na bunga ng iyong maingat na mga aksyon. ');
INSERT INTO quotes VALUES(131,'effort',replace(' \nYour focus and determination create high-quality results. ','\n',char(10)),' Ang iyong pagkakatuon at determinasyon ay lumilikha ng mataas na kalidad na mga resulta. ');
INSERT INTO quotes VALUES(132,'effort','Effort brings great rewards when persistence overcomes challenges.','Ang pagpupunyagi ay nagdudulot ng malalaking gantimpala kapag nalampasan ang mga pagsubok.');
INSERT INTO quotes VALUES(133,'effort',replace('\nSuccess blooms when perseverance outshines obstacles.','\n',char(10)),'Tagumpay ay natatamasa kapag ang pagtitiyaga ay higit sa mga hadlang.');
INSERT INTO quotes VALUES(134,'effort',replace('\nStrength comes from not giving up despite difficulties.','\n',char(10)),'Ang lakas ay nagmumula sa hindi pagbibigay-kahit sa mga hamon.');
INSERT INTO quotes VALUES(135,'effort',replace('\nResilience is key to unlocking the full potential of efforts.','\n',char(10)),'Ang pagiging matatag ang susi sa pagpapalabas ng buong potensyal ng pagsisikap.');
INSERT INTO quotes VALUES(136,'effort',replace('\nPersistence paves the way for success to flourish.','\n',char(10)),'Ang patuloy na pagpupursige ay nagbubukas ng daan para sa tagumpay na mamunga.');
INSERT INTO quotes VALUES(137,'happy','You radiate joy despite the seasons. ','Ipinapahayag mo ang tuwa kahit anong panahon.');
INSERT INTO quotes VALUES(138,'happy',replace(' \nEvery moment is a chance for happiness. ','\n',char(10)),'Bawat sandali ay pagkakataon para sa kaligayahan.');
INSERT INTO quotes VALUES(139,'happy',replace('\nYour happiness transcends any season. ','\n',char(10)),'Ang iyong kaligayahan ay lampas sa anumang panahon.');
INSERT INTO quotes VALUES(140,'happy',replace('\nYour joy is not dependent on the weather. ','\n',char(10)),'Hindi umaasa ang iyong kasiyahan sa panahon.');
INSERT INTO quotes VALUES(141,'happy',replace('\nHappiness blooms in your heart, rain or shine. ','\n',char(10)),'Nagmumula ang kaligayahan sa iyong puso, sa init man o ulan.');
INSERT INTO quotes VALUES(142,'happy','All my happiness comes from within. ','Ang lahat ng kaligayahan ko ay nagmumula sa loob.');
INSERT INTO quotes VALUES(143,'happy',replace('\nI prioritize connection over technology. ','\n',char(10)),'Mas pinili kong magkaroon ng koneksyon kaysa teknolohiya.');
INSERT INTO quotes VALUES(144,'happy',replace('\nI find joy in simple moments without technology. ','\n',char(10)),'Nakakahanap ako ng ligaya sa simpleng sandali nang walang teknolohiya.');
INSERT INTO quotes VALUES(145,'happy',replace('\nMy happiness is not dependent on material things. ','\n',char(10)),'Ang kaligayahan ko ay hindi nakadepende sa materyal na bagay.');
INSERT INTO quotes VALUES(146,'happy',replace('\nI cherish real-life experiences over virtual ones. ','\n',char(10)),'Pinahahalagahan ko ang mga tunay na karanasan kaysa sa virtual.');
INSERT INTO quotes VALUES(147,'happy','May all beings have happy minds. ',' Nawa''y magkaroon ng masayang isipan ang lahat ng nilalang. ');
INSERT INTO quotes VALUES(148,'happy',replace(' \n\nMay peace dwell in every heart. ','\n',char(10)),' Nawa''y manirahan ang kapayapaan sa bawat puso. ');
INSERT INTO quotes VALUES(149,'happy',replace(' \n\nJoy is found in every moment. ','\n',char(10)),' Ang kasiyahan ay matatagpuan sa bawat sandali. ');
INSERT INTO quotes VALUES(150,'happy',replace(' \n\nLove surrounds me at all times. ','\n',char(10)),' Ang pagmamahal ay bumabalot sa akin sa lahat ng oras. ');
INSERT INTO quotes VALUES(151,'happy',replace(' \n\nI radiate positivity and light. ','\n',char(10)),' Ako''y nagpapalabas ng positibong enerhiya at liwanag. ');
INSERT INTO quotes VALUES(152,'life','Life is about perfect timing. ',' Ang buhay ay tungkol sa tamang panahon.');
INSERT INTO quotes VALUES(153,'life',replace('\n\nTrust the process of life''s timing. ','\n',char(10)),' Tiwala sa proseso ng pagtatakda ng buhay.');
INSERT INTO quotes VALUES(154,'life',replace('\n\nEmbrace the flow of life''s timing. ','\n',char(10)),' Tanggapin ang agos ng pagtatakda ng buhay.');
INSERT INTO quotes VALUES(155,'life',replace('\n\nI am in sync with life''s timing. ','\n',char(10)),' Ako ay kasama sa tamang panahon ng buhay.');
INSERT INTO quotes VALUES(156,'life',replace('\n\nI trust in the divine timing of my life. ','\n',char(10)),' Ako ay nagtitiwala sa banal na pagtatakda ng aking buhay.');
INSERT INTO quotes VALUES(157,'life','You cherish every moment in life''s journey.','Iniingatan mo ang bawat sandali sa paglalakbay ng buhay.');
INSERT INTO quotes VALUES(158,'life',replace('\nYou make the most of every opportunity.','\n',char(10)),'Pinapahalagahan mo ang bawat pagkakataon.');
INSERT INTO quotes VALUES(159,'life',replace('\nYou live in the present and savor each day.','\n',char(10)),'Ibinubuhay mo ang kasalukuyan at sinusulit ang bawat araw.');
INSERT INTO quotes VALUES(160,'life',replace('\nYou prioritize what truly matters in life.','\n',char(10)),'Ibinibigay mo ang prayoridad sa mga bagay na tunay na mahalaga sa buhay.');
INSERT INTO quotes VALUES(161,'life',replace('\nYou understand the value of time and use it wisely.','\n',char(10)),'Naiintindihan mo ang halaga ng oras at ginagamit ito nang wasto.');
INSERT INTO quotes VALUES(162,'life','You attract kindness by showing kindness.','Nakakakuha ka ng kabaitan sa pamamagitan ng pagpapakita ng kabaitan.');
INSERT INTO quotes VALUES(163,'life',replace('\nYou deserve respect and love.','\n',char(10)),'Karapat-dapat ka sa respeto at pagmamahal.');
INSERT INTO quotes VALUES(164,'life',replace('\nSet boundaries to receive healthy relationships.','\n',char(10)),'Maglagay ng hangganan upang makatanggap ng malusog na relasyon.');
INSERT INTO quotes VALUES(165,'life',replace('\nTeach others to value you by valuing yourself.','\n',char(10)),'Turuan ang iba na pahalagahan ka sa pamamagitan ng pagpapahalaga sa sarili.');
INSERT INTO quotes VALUES(166,'life',replace('\nYour self-worth sets the standard for others.','\n',char(10)),'Ang iyong halaga sa sarili ang nagtatakda ng pamantayan para sa iba.');
INSERT INTO quotes VALUES(167,'life','You are in control of shaping your own path. ',' Ikaw ang may hawak sa pagbuo ng iyong sariling landas. ');
INSERT INTO quotes VALUES(168,'life',replace(' \nYour journey is about self-discovery and growth. ','\n',char(10)),' Ang iyong paglalakbay ay tungkol sa pagtuklas at pag-unlad sa sarili. ');
INSERT INTO quotes VALUES(169,'life',replace(' \nEmbrace the power within you to evolve. ','\n',char(10)),' Yakapin ang lakas sa loob mo upang magbago. ');
INSERT INTO quotes VALUES(170,'life',replace(' \nEvery day is a chance to craft the best version of yourself. ','\n',char(10)),' Ang bawat araw ay pagkakataon upang maging pinakamahusay na bersyon ng sarili. ');
INSERT INTO quotes VALUES(171,'life',replace(' \nBelieve in your ability to shape a brighter future. ','\n',char(10)),' Maniwala sa kakayahan mo na magpanday ng mas magandang kinabukasan. ');
INSERT INTO quotes VALUES(172,'life','You radiate life''s energy and live fully in success. ',' Ikaw ay naglalabas ng enerhiya ng buhay at nabubuhay nang buo sa tagumpay. ');
INSERT INTO quotes VALUES(173,'life',replace(' \nYou are capable of living a successful life filled with energy. ','\n',char(10)),' Ikaw ay kaya ng mabuhay nang matagumpay na puno ng enerhiya. ');
INSERT INTO quotes VALUES(174,'life',replace('\nYour vibrant energy attracts success into your life. ','\n',char(10)),' Ang iyong mabangis na enerhiya ay humahatak ng tagumpay sa iyong buhay. ');
INSERT INTO quotes VALUES(175,'life',replace('\nSuccess follows you as you live life to the fullest. ','\n',char(10)),' Ang tagumpay ay sumusunod sa iyo habang ikaw ay nabubuhay nang buo. ');
INSERT INTO quotes VALUES(176,'life',replace('\nLiving with energy and zest leads to a prosperous life. ','\n',char(10)),' Ang pagbuhay nang may enerhiya at sigla ay nagdudulot ng maunlad na buhay. ');
INSERT INTO quotes VALUES(177,'confidence','Kindness radiates confidence within me. ','Ang kabaitan sa salita ay lumilikha ng kumpiyansa sa sarili.');
INSERT INTO quotes VALUES(178,'confidence',replace('\nKindness deepens my thoughts. ','\n',char(10)),'Ang kabaitan sa pag-iisip ay nagpapalalim ng kaalaman.');
INSERT INTO quotes VALUES(179,'confidence',replace('\nKindness in giving fosters love around me. ','\n',char(10)),'Ang kabaitan sa pagbibigay ay lumilikha ng pagmamahal sa paligid.');
INSERT INTO quotes VALUES(180,'confidence','Optimism fuels my path to success. ',replace(' Ang optimismo ang nagbubunga ng tagumpay.\nHope and confidence guide me through challenges. ','\n',char(10)));
INSERT INTO quotes VALUES(181,'confidence','I believe in my potential to create positive change. ',' Naniniwala ako sa aking potensyal na makapagdulot ng positibong pagbabago. ');
INSERT INTO quotes VALUES(182,'confidence',replace(' \n\nI trust in my abilities to make a difference. ','\n',char(10)),' Tinitiwala ko sa aking kakayahan na makapagbigay ng pagbabago. ');
INSERT INTO quotes VALUES(183,'confidence',replace(' \n\nMy self-confidence empowers me to improve the world. ','\n',char(10)),' Ang aking tiwala sa sarili ay nagbibigay sa akin ng lakas upang mapabuti ang mundo. ');
INSERT INTO quotes VALUES(184,'confidence',replace(' \n\nI am capable of building a better world with my skills. ','\n',char(10)),' Kayang-kaya kong itayo ang isang mas magandang mundo gamit ang aking mga kakayahan. ');
INSERT INTO quotes VALUES(185,'confidence',replace(' \n\nI embrace my potential to create a brighter future. ','\n',char(10)),' Tinatanggap ko ang aking potensyal upang luwagin ang hinaharap. ');
INSERT INTO quotes VALUES(186,'confidence',replace('\nRadiate positivity and attract good vibes into your life.\n','\n',char(10)),'Ipagkalat ang positibong enerhiya at magdala ng magandang bagay sa iyong buhay.');
INSERT INTO quotes VALUES(187,'confidence',replace('\nEmbrace challenges as opportunities for growth and learning.\n','\n',char(10)),'Tanggapin ang mga hamon bilang pagkakataon para sa pag-unlad at pag-aaral.');
INSERT INTO quotes VALUES(188,'confidence',replace('\nStay true to yourself and let your authenticity shine brightly.\n','\n',char(10)),'Manatiling tapat sa sarili at hayaang magningning ang iyong katotohanan.');
INSERT INTO quotes VALUES(189,'confidence','I am capable of solving my own problems with confidence. ',' Kaya kong malutas ang aking mga problema nang may tiwala. ');
INSERT INTO quotes VALUES(190,'confidence',replace(' \nMy confidence is a powerful tool in overcoming challenges. ','\n',char(10)),' Ang aking tiwala ay isang makapangyarihang sandata sa pagharap sa mga hamon. ');
INSERT INTO quotes VALUES(191,'confidence',replace(' \nI trust in my ability to seek guidance and support when needed. ','\n',char(10)),' Ako''y naniniwala sa aking kakayahan na humingi ng gabay at suporta kapag kinakailangan. ');
INSERT INTO quotes VALUES(192,'confidence',replace(' \nMy belief in myself empowers me to face any obstacle. ','\n',char(10)),' Ang aking paniniwala sa sarili ay nagbibigay sa akin ng lakas na harapin ang anumang hadlang. ');
INSERT INTO quotes VALUES(193,'confidence',replace(' \nI am grateful for the unwavering confidence of my friends. ','\n',char(10)),' Lubos akong nagpapasalamat sa di-matitinag na tiwala ng aking mga kaibigan. ');
INSERT INTO quotes VALUES(194,'trust','Believe in yourself and watch success unfold. ',' Maniwala sa sarili at makita ang tagumpay.');
INSERT INTO quotes VALUES(195,'trust',replace('\nYou have the power to achieve your goals. ','\n',char(10)),' May kakayahan ka para maabot ang iyong mga layunin.');
INSERT INTO quotes VALUES(196,'trust',replace('\nTrust your instincts, they lead to success. ','\n',char(10)),' Tiwalaan ang iyong mga instikto, sila''y patungo sa tagumpay.');
INSERT INTO quotes VALUES(197,'trust',replace('\nSuccess starts with trusting yourself. ','\n',char(10)),' Ang tagumpay ay nagsisimula sa pagtitiwala sa sarili.');
INSERT INTO quotes VALUES(198,'trust',replace('\nSelf-belief paves the way for success. ','\n',char(10)),' Ang paniniwala sa sarili ay nagbubukas daan sa tagumpay.');
INSERT INTO quotes VALUES(199,'trust','Love and kindness guide my actions always. ','Ang pagmamahal at kabutihan ang nagtuturo sa aking mga kilos palagi.');
INSERT INTO quotes VALUES(200,'trust',replace('\nI trust in the goodness of others. ','\n',char(10)),'Ako ay naniniwala sa kabutihan ng iba.');
INSERT INTO quotes VALUES(201,'trust',replace('\nI choose to do right by everyone. ','\n',char(10)),'Pinili kong gawin ang tama para sa lahat.');
INSERT INTO quotes VALUES(202,'trust',replace('\nMy heart is open to love unconditionally. ','\n',char(10)),'Ang aking puso ay bukas sa walang kondisyon na pagmamahal.');
INSERT INTO quotes VALUES(203,'trust',replace('\nI treat others with respect and compassion. ','\n',char(10)),'Ipinapakita ko ang respeto at habag sa iba.');
INSERT INTO quotes VALUES(204,'trust','Trust yourself. You know more than you think you do.','Tiawag ka sa imo kaugalingon. Kabalo ka pa sang indi mo pagtoo.');
INSERT INTO quotes VALUES(205,'trust',replace('\nBelieve in yourself. You possess more knowledge than you realize.','\n',char(10)),'Maniwala sa sarili. Ikaw ay may higit pang kaalaman kaysa sa iyong iniisip.');
INSERT INTO quotes VALUES(206,'trust',replace('\nHave faith in yourself. Your capabilities exceed your doubts.','\n',char(10)),'Magtiwala sa iyong sarili. Ang iyong kakayahan ay lampas sa iyong pag-aalinlangan.');
INSERT INTO quotes VALUES(207,'trust',replace('\nEmbrace your wisdom. You hold more answers than you imagine.','\n',char(10)),'Tanggapin ang iyong karunungan. Ikaw ay may higit pang mga sagot kaysa sa iyong iniisip.');
INSERT INTO quotes VALUES(208,'confidence','Kindness radiates confidence in others. ','Ang kabaitan ay bumibigay ng kumpiyansa sa iba.');
INSERT INTO quotes VALUES(209,'confidence',replace('\nKindness nurtures deep thinking within. ','\n',char(10)),'Ang kabaitan ay nagbibigay-buhay sa malalim na pag-iisip.');
INSERT INTO quotes VALUES(210,'confidence',replace('\nKindness fosters love through giving. ','\n',char(10)),'Ang kabaitan ay nagtataguyod ng pagmamahal sa pamamagitan ng pagbibigay.');
INSERT INTO quotes VALUES(211,'confidence','Kindness is my language of confidence and compassion.','Ang kabaitan sa salita ay lumilikha ng kumpiyansa at habag.');
INSERT INTO quotes VALUES(212,'hope','I find hope in the darkest of days. ','Nakakahanap ako ng pag-asa sa pinakamadilim na mga araw.');
INSERT INTO quotes VALUES(213,'hope',replace('\nI focus in the brightest. ','\n',char(10)),'Nagfo-focus ako sa pinakamaliwanag.');
INSERT INTO quotes VALUES(214,'hope',replace('\nI do not judge the universe. ','\n',char(10)),'Hindi ko hinuhusgahan ang sansinukob.');
INSERT INTO quotes VALUES(215,'hope','You have meaningful pursuits that bring joy into your life.','Mayroon kang mga bagay na may saysay na nagdudulot ng kasiyahan sa iyong buhay.');
INSERT INTO quotes VALUES(216,'hope',replace('\nYour heart is filled with love and compassion for others.','\n',char(10)),'Ang iyong puso ay puno ng pagmamahal at habag para sa iba.');
INSERT INTO quotes VALUES(217,'hope','Embracing paradoxes leads to growth and breakthroughs. ',' Ang pagtanggap sa mga paradoks ay nagdudulot ng pag-unlad at tagumpay.');
INSERT INTO quotes VALUES(218,'hope',replace('\nEvery challenge brings opportunity for growth and learning. ','\n',char(10)),' Ang bawat hamon ay nagdudulot ng pagkakataon para sa pag-unlad at kaalaman.');
INSERT INTO quotes VALUES(219,'hope',replace('\nWe find strength in facing contradictions head-on. ','\n',char(10)),' Natututunan natin ang lakas sa harapin ang mga pagtutol nang diretso.');
INSERT INTO quotes VALUES(220,'hope',replace('\nAcknowledging paradoxes opens doors to new possibilities. ','\n',char(10)),' Ang pagtanggap sa mga paradoks ay nagbubukas ng mga bagong posibilidad.');
INSERT INTO quotes VALUES(221,'hope',replace('\nContradictions fuel our journey towards growth and enlightenment. ','\n',char(10)),' Ang mga pagtutol ay nagpapalakas sa ating paglalakbay patungo sa pag-unlad at kaalaman.');
INSERT INTO quotes VALUES(222,'hope','I rely on facts to strengthen my beliefs. ',' Naniniwala ako sa katotohanan upang palakasin ang aking paniniwala.');
INSERT INTO quotes VALUES(223,'hope',replace(' \nI choose to build my faith on truth, not fiction. ','\n',char(10)),' Pinipili kong itayo ang aking pananampalataya sa katotohanan, hindi sa kathang-isip.');
INSERT INTO quotes VALUES(224,'hope',replace(' \nMy hope is anchored on reality, not false promises. ','\n',char(10)),' Ang aking pag-asa ay nakasalalay sa realidad, hindi sa mga pangakong hindi totoo.');
INSERT INTO quotes VALUES(225,'hope',replace(' \nI trust in what is real to guide my beliefs. ','\n',char(10)),' Ako''y nagtitiwala sa mga bagay na totoo upang gabayan ang aking paniniwala.');
INSERT INTO quotes VALUES(226,'hope',replace(' \nI cultivate a strong foundation of faith based on truth. ','\n',char(10)),' Ako''y nagtataguyod ng matibay na pundasyon ng pananampalataya na nakabatay sa katotohanan.');
INSERT INTO quotes VALUES(227,'hope','Believe in your capabilities and watch success unfold. ',' Maniwala sa iyong kakayahan at makita ang tagumpay. ');
INSERT INTO quotes VALUES(228,'hope',replace(' \nStay hopeful and confident in your journey towards greatness. ','\n',char(10)),' Manatiling puno ng pag-asa at tiwala sa iyong paglalakbay patungo sa kagalingan. ');
INSERT INTO quotes VALUES(229,'hope',replace(' \nLet optimism guide you to your goals and dreams. ','\n',char(10)),' Pabayaang magdala sa iyo ng optimismo patungo sa iyong mga layunin at pangarap. ');
INSERT INTO quotes VALUES(230,'hope',replace(' \nTrust in the power of positivity to bring accomplishments. ','\n',char(10)),' Tiwala sa kapangyarihan ng positibong pag-iisip upang makamit ang tagumpay. ');
INSERT INTO quotes VALUES(231,'hope',replace(' \nEmbrace hope and self-assurance for a fruitful path. ','\n',char(10)),' Yakapin ang pag-asa at sarili mong kumpiyansa para sa isang mapagpalaing landas. ');
INSERT INTO quotes VALUES(232,'hope','You embody simplicity and greatness. Believe in freedom, justice, and hope!','Ikaw ay sumasagisag sa kasimplehan at kahalagahan. Maniwala sa kalayaan, katarungan, at pag-asa!');
INSERT INTO quotes VALUES(233,'hope','Simplicity is key to greatness. Live by freedom, justice, and hope!','Ang kasimplehan ang susi sa kahalagahan. Mabuhay sa kalayaan, katarungan, at pag-asa!');
INSERT INTO quotes VALUES(234,'hope','Greatness dwells in simplicity. Uphold honor, duty, and mercy!','Ang kahalagahan ay naninirahan sa kasimplehan. Itaguyod ang dangal, tungkulin, at awa!');
INSERT INTO quotes VALUES(235,'hope','Believe in simple yet great things. Cherish freedom, justice, and hope!','Maniwala sa simpleng ngunit mahahalagang bagay. Pahalagahan ang kalayaan, katarungan, at pag-asa!');
INSERT INTO quotes VALUES(236,'love',replace('Do all things with love.\n','\n',char(10)),'Gawin ang lahat ng bagay nang may pag-ibig.');
INSERT INTO quotes VALUES(237,'love',replace('\nBelieve in your own strength.\n','\n',char(10)),'Maniwala sa iyong sariling lakas.');
INSERT INTO quotes VALUES(238,'love',replace('\nEmbrace the journey of growth.\n','\n',char(10)),'Tanggapin ang paglalakbay ng pag-unlad.');
INSERT INTO quotes VALUES(239,'love',replace('\nRadiate positivity and kindness.\n','\n',char(10)),'Magbigay-liwanag ng positivity at kabutihan.');
INSERT INTO quotes VALUES(240,'love',replace('\nFind joy in every moment.\n','\n',char(10)),'Hanapin ang kasiyahan sa bawat sandali.');
INSERT INTO quotes VALUES(241,'love','You are never too old to experience love''s magic. ',' Hindi ka kailanman masyadong matanda para sa mahika ng pag-ibig.');
INSERT INTO quotes VALUES(242,'love',replace('\nEmbrace love in all stages of life. ','\n',char(10)),' Yakapin ang pag-ibig sa lahat ng yugto ng buhay.');
INSERT INTO quotes VALUES(243,'love',replace('\nLove is timeless, it transcends age barriers. ','\n',char(10)),' Ang pag-ibig ay walang hanggan, ito''y lampas sa hadlang ng edad.');
INSERT INTO quotes VALUES(244,'love',replace('\nLet love be your shield against the passing of time. ','\n',char(10)),' Hayaan mong maging tanggulan ang pag-ibig laban sa paglipas ng panahon.');
INSERT INTO quotes VALUES(245,'love',replace('\nEvery moment with love adds youth to your soul. ','\n',char(10)),' Bawat sandali na may pag-ibig ay nagdadagdag ng kabataan sa iyong kaluluwa.');
INSERT INTO quotes VALUES(246,'love','I attract greatness by loving what I do. ','Ako ay nakakaakit ng kadakilaan sa pamamagitan ng pagmamahal sa aking ginagawa.');
INSERT INTO quotes VALUES(247,'love',replace(' \nI cultivate admiration for my passions. ','\n',char(10)),'Ako ay nagpapalakas ng paghanga para sa aking mga hilig.');
INSERT INTO quotes VALUES(248,'love',replace(' \nPositivity and love lead me to success. ','\n',char(10)),'Ang positibong pananaw at pagmamahal ang nagdadala sa akin sa tagumpay.');
INSERT INTO quotes VALUES(249,'love',replace(' \nI welcome success by loving my craft. ','\n',char(10)),'Ako ay bumabati ng tagumpay sa pamamagitan ng pagmamahal sa aking sining.');
INSERT INTO quotes VALUES(250,'love',replace(' \nLove and dedication attract abundance to me. ','\n',char(10)),'Ang pagmamahal at dedikasyon ay nakakaakit ng kasaganaan sa akin.');
INSERT INTO quotes VALUES(251,'love','Love makes my journey beautiful and meaningful. ',' Ang pag-ibig ang nagpapaganda at nagbibigay halaga sa aking paglalakbay.');
INSERT INTO quotes VALUES(252,'love',replace(' \nI am deserving of love that makes life worthwhile. ','\n',char(10)),' Ako ay karapat-dapat sa pag-ibig na nagpapahalaga sa buhay.');
INSERT INTO quotes VALUES(253,'love',replace(' \nMy heart is open to giving and receiving love. ','\n',char(10)),' Ang aking puso ay bukas sa pagbibigay at pagtanggap ng pag-ibig.');
INSERT INTO quotes VALUES(254,'love',replace(' \nI radiate love and positivity in everything I do. ','\n',char(10)),' Aking pinapakita ang pag-ibig at positibong aura sa lahat ng aking ginagawa.');
INSERT INTO quotes VALUES(255,'love',replace(' \nI choose to see the beauty and love in every moment. ','\n',char(10)),' Pinili kong makita ang ganda at pag-ibig sa bawat sandali.');
INSERT INTO quotes VALUES(256,'peace','I can learn new skills quickly and efficiently.',replace('Kaya kong matutunan ng mabilis at mabisa.\n','\n',char(10)));
INSERT INTO quotes VALUES(257,'peace','I am capable of accomplishing challenging tasks.',replace('Kaya kong magawa ang mga mahihirap na gawain.\n','\n',char(10)));
INSERT INTO quotes VALUES(258,'peace','I have the ability to absorb information rapidly.',replace('May kakayahan akong ma-absorb ang impormasyon ng mabilis.\n','\n',char(10)));
INSERT INTO quotes VALUES(259,'peace','I am a fast learner and can adapt easily.',replace('Mabilis akong mag-aral at madaling makapag-adjust.\n','\n',char(10)));
INSERT INTO quotes VALUES(260,'peace','I can tackle complex topics with ease.','Kaya kong harapin ang mga komplikadong paksa nang madali.');
INSERT INTO quotes VALUES(261,'peace','You bring peace with your meaningful words. ',' Nagdudulot ka ng kapayapaan sa pamamagitan ng iyong makabuluhang mga salita. ');
INSERT INTO quotes VALUES(262,'peace',replace('\nYour words have power to bring calmness. ','\n',char(10)),' Ang iyong mga salita ay may kapangyarihan na magdulot ng kalinisan. ');
INSERT INTO quotes VALUES(263,'peace',replace('\nSpeak one useful word, create peace. ','\n',char(10)),' Magsalita ng isang makabuluhang salita, lumikha ng kapayapaan. ');
INSERT INTO quotes VALUES(264,'peace',replace('\nYour words have the power to soothe. ','\n',char(10)),' Ang iyong mga salita ay may kapangyarihan na magpahupa ng sama ng loob. ');
INSERT INTO quotes VALUES(265,'peace',replace('\nChoose words that bring serenity. ','\n',char(10)),' Piliin ang mga salitang nagdudulot ng katahimikan. ');
INSERT INTO quotes VALUES(266,'peace','May I spread love where there''s hate. ',' Nawa''y maipamahagi ko ang pag-ibig kung saan may poot.');
INSERT INTO quotes VALUES(267,'peace',replace('\nMy actions bring peace and love. ','\n',char(10)),' Ang aking mga kilos ay nagdadala ng kapayapaan at pagmamahal.');
INSERT INTO quotes VALUES(268,'peace',replace('\nI am a beacon of peace and love. ','\n',char(10)),' Ako ay isang tanglaw ng kapayapaan at pagmamahal.');
INSERT INTO quotes VALUES(269,'peace',replace('\nIn every conflict, I choose love. ','\n',char(10)),' Sa bawat alitan, pinipili ko ang pag-ibig.');
INSERT INTO quotes VALUES(270,'peace',replace('\nI radiate peace and kindness. ','\n',char(10)),' Aking pinananatili ang kapayapaan at kabutihan.');
INSERT INTO quotes VALUES(271,'peace','You embrace your true self and find peace within. ','Tanggapin mo ang tunay mong sarili at makahanap ng kapayapaan sa loob.');
INSERT INTO quotes VALUES(272,'peace',replace('\nYou appreciate your unique qualities and find contentment. ','\n',char(10)),'Pinahahalagahan mo ang iyong natatanging katangian at natatagpuan ang kasiyahan.');
INSERT INTO quotes VALUES(273,'peace',replace('\nYou are grateful for the present moment and everything you have. ','\n',char(10)),'Nagpapasalamat ka sa kasalukuyang sandali at sa lahat ng bagay na meron ka.');
INSERT INTO quotes VALUES(274,'peace',replace('\nYou radiate positivity and attract abundance effortlessly. ','\n',char(10)),'Naglalabas ka ng positibong enerhiya at madaling dumadating ang kasaganaan.');
INSERT INTO quotes VALUES(275,'peace',replace('\nYou believe in yourself and trust the journey ahead. ','\n',char(10)),'Naniniwala ka sa sarili at nagtitiwala sa darating na paglalakbay.');
INSERT INTO quotes VALUES(276,'peace','Embrace your true self and find contentment in what you possess.','Tanggapin ang iyong tunay na sarili at mahanap ang kasiyahan sa mga bagay na meron ka.');
INSERT INTO quotes VALUES(277,'peace',replace('\nLove and accept yourself fully to attract abundance effortlessly.','\n',char(10)),'Mahalin at tanggapin ang sarili mo ng buong-buo upang madaling ma-attract ang kasaganaan.');
INSERT INTO quotes VALUES(278,'peace',replace('\nPeace within yourself brings harmony to your external world.','\n',char(10)),'Ang kapayapaan sa iyong sarili ay nagdadala ng harmonya sa iyong mundo.');
INSERT INTO quotes VALUES(279,'peace',replace('\nGratitude for who you are opens the door to endless possibilities.','\n',char(10)),'Pasasalamat sa kung sino ka ay nagbubukas ng pinto sa walang katapusang mga posibilidad.');
INSERT INTO quotes VALUES(280,'peace',replace('\nYour self-worth is the foundation of your happiness and success.','\n',char(10)),'Ang iyong halaga sa sarili ang pundasyon ng iyong kaligayahan at tagumpay.');
INSERT INTO quotes VALUES(281,'peace','Gratitude shapes my past, brings peace today, and inspires my future. ',' Ang pasasalamat ay bumubuo sa aking nakaraan, nagdudulot ng kapayapaan ngayon, at nagbibigay inspirasyon sa aking kinabukasan. ');
INSERT INTO quotes VALUES(282,'joy','You find joy in your achievements and creative endeavors.','Natatagpuan mo ang kasiyahan sa iyong mga tagumpay at pagsisikap sa kreatibidad.');
INSERT INTO quotes VALUES(283,'joy',replace('\nYour happiness is not defined by material wealth alone.','\n',char(10)),'Ang iyong kaligayahan ay hindi lamang nasusukat sa yaman.');
INSERT INTO quotes VALUES(284,'joy',replace('\nYou cherish the thrill that comes from your creative pursuits.','\n',char(10)),'Ipinapahalaga mo ang sigla na nagmumula sa iyong mga proyektong kreatibo.');
INSERT INTO quotes VALUES(285,'joy',replace('\nYour achievements bring you lasting happiness.','\n',char(10)),'Ang iyong mga tagumpay ay nagdudulot sa iyo ng matagalang kaligayahan.');
INSERT INTO quotes VALUES(286,'joy',replace('\nYou understand that happiness is found in personal growth.','\n',char(10)),'Naiintindihan mo na ang kaligayahan ay matatagpuan sa pag-unlad ng iyong sarili.');
INSERT INTO quotes VALUES(287,'joy','Friendship brings joy and lessens sorrow. ',' Ang pagkakaibigan ay nagdudulot ng kasiyahan at nagpapaliit ng lungkot.');
INSERT INTO quotes VALUES(288,'joy',replace('\nFriendship doubles joy and divides grief. ','\n',char(10)),' Ang pagkakaibigan ay nagdodoble ng kasiyahan at nagbabawas ng lungkot.');
INSERT INTO quotes VALUES(289,'joy',replace('\nFriendship is a source of happiness. ','\n',char(10)),' Ang pagkakaibigan ay pinagmumulan ng kasiyahan.');
INSERT INTO quotes VALUES(290,'joy',replace('\nFriendship is a remedy for misery. ','\n',char(10)),' Ang pagkakaibigan ay lunas sa lungkot.');
INSERT INTO quotes VALUES(291,'joy',replace('\nFriendship is a gift that multiplies blessings. ','\n',char(10)),' Ang pagkakaibigan ay regalo na nagpaparami ng biyaya.');
INSERT INTO quotes VALUES(292,'joy','You are capable of being brave and patient in times of challenge.','Kayang-kaya mong maging matapang at mapagpasensya sa mga oras ng pagsubok.');
INSERT INTO quotes VALUES(293,'joy',replace('\nStrength grows from facing difficulties with courage and resilience.','\n',char(10)),'Lumalakas ang iyong lakas sa pagharap sa mga pagsubok nang may tapang at tibay ng loob.');
INSERT INTO quotes VALUES(294,'joy',replace('\nChallenges are opportunities to cultivate bravery and resilience.','\n',char(10)),'Ang mga hamon ay pagkakataon upang palakasin ang tapang at tibay ng loob.');
INSERT INTO quotes VALUES(295,'joy',replace('\nYour courage and patience shine brightest during tough times.','\n',char(10)),'Ang iyong tapang at pasensya ay lalong kumikinang sa panahon ng mga pagsubok.');
INSERT INTO quotes VALUES(296,'joy',replace('\nEmbrace challenges as stepping stones to courage and growth.','\n',char(10)),'Tanggapin ang mga hamon bilang hakbang patungo sa tapang at pag-unlad.');
INSERT INTO quotes VALUES(297,'joy','You are skilled in nurturing joy through creativity and learning. ',' Ikaw ay bihasa sa pagpapalago ng kasiyahan sa pamamagitan ng kreatibidad at kaalaman. ');
INSERT INTO quotes VALUES(298,'joy',' You inspire joy and creativity in others effortlessly. ',' Ikaw ay nagbibigay inspirasyon ng kasiyahan at kreatibidad sa iba nang walang anumang pagod. ');
INSERT INTO quotes VALUES(299,'joy',' Your passion for teaching brings joy and enlightenment. ',' Ang iyong pagmamahal sa pagtuturo ay nagdudulot ng kasiyahan at kaalaman. ');
INSERT INTO quotes VALUES(300,'joy',' You possess the gift of igniting joy through teaching. ',' Ikaw ay mayroong kagalingan sa pagpapalaganap ng kasiyahan sa pamamagitan ng pagtuturo. ');
INSERT INTO quotes VALUES(301,'joy',' Your teaching style radiates joy and passion for learning. ',' Ang iyong estilo ng pagtuturo ay sumasalamin ng kasiyahan at pagmamahal sa pag-aaral. ');
INSERT INTO quotes VALUES(302,'joy','Joy flows naturally from a heart at peace. ',' Ang kasiyahan ay nagmumula nang natural mula sa isang puso na mapayapa. ');
INSERT INTO quotes VALUES(303,'joy',replace(' \nI release any guilt and welcome happiness. ','\n',char(10)),' Tinatanggal ko ang anumang pagkukulang at tinatanggap ang kaligayahan. ');
INSERT INTO quotes VALUES(304,'joy',replace(' \nI choose to let go of regrets and embrace joy. ','\n',char(10)),' Pinipili kong kalimutan ang pagsisisi at yakapin ang kasiyahan. ');
INSERT INTO quotes VALUES(305,'joy',replace(' \nI am deserving of joy and peace in my life. ','\n',char(10)),' Karapat-dapat ako sa kasiyahan at kapayapaan sa aking buhay. ');
INSERT INTO quotes VALUES(306,'joy',replace(' \nI attract positivity by releasing all regrets. ','\n',char(10)),' Ako''y nag-aattract ng positibong bagay sa pamamagitan ng pagpapakawala sa anumang pagsisisi. ');
INSERT INTO quotes VALUES(307,'joy','We embrace joy by seeing the goodness in our lives. ',' Natatanggap natin ang kasiyahan sa pagkilala sa kagandahan ng buhay. ');
INSERT INTO quotes VALUES(308,'joy',replace(' \nWe choose to see the positive side of life, inviting joy in. ','\n',char(10)),' Pinipili natin ang positibong pananaw sa buhay, inaanyayahan ang kasiyahan. ');
INSERT INTO quotes VALUES(309,'joy',replace(' \nGratitude opens the door for joy to enter our hearts. ','\n',char(10)),' Ang pasasalamat ay nagbubukas ng pinto para makapasok ang kasiyahan sa ating mga puso. ');
INSERT INTO quotes VALUES(310,'joy',replace(' \nOur perspective shapes our joy; focus on the good. ','\n',char(10)),' Ang ating pananaw ang bumubuo ng kasiyahan natin; itungkol sa kabutihan. ');
INSERT INTO quotes VALUES(311,'joy',replace(' \nLetting go of negativity allows joy to radiate within. ','\n',char(10)),' Ang pagpapakawala sa negatibidad ay nagbibigay-daan sa kasiyahan na magliwanag sa loob natin. ');
INSERT INTO quotes VALUES(312,'life','Character develops itself in the stream of life. ',' Ang pagkatao ay lumalago sa agos ng buhay.');
INSERT INTO quotes VALUES(313,'life',replace('\n\nBelieve in the power of your growth and resilience. ','\n',char(10)),' Maniwala sa kapangyarihan ng iyong pag-unlad at pagtibay.');
INSERT INTO quotes VALUES(314,'life',replace('\n\nEmbrace challenges as opportunities for growth. ','\n',char(10)),' Tanggapin ang mga hamon bilang pagkakataon sa pag-unlad.');
INSERT INTO quotes VALUES(315,'life',replace('\n\nTrust in your ability to overcome any obstacles. ','\n',char(10)),' Tiwala sa kakayahan mong lampasan ang anumang hadlang.');
INSERT INTO quotes VALUES(316,'life',replace('\n\nYour journey is shaping you into a stronger version of yourself. ','\n',char(10)),' Ang iyong paglalakbay ay nagpapalakas sa iyong pagkatao.');
INSERT INTO quotes VALUES(317,'life','Love gives me the strength to live fully.','Ang pagmamahal ang nagbibigay sa akin ng lakas upang mabuhay na buo.');
INSERT INTO quotes VALUES(318,'life',replace('\nI choose to fill my life with love and joy.','\n',char(10)),'Pinili kong punuin ang aking buhay ng pagmamahal at ligaya.');
INSERT INTO quotes VALUES(319,'life',replace('\nI am deserving of love and all the good it brings.','\n',char(10)),'Karapat-dapat ako sa pagmamahal at sa lahat ng mabuting dulot nito.');
INSERT INTO quotes VALUES(320,'life',replace('\nLove is abundant in my life, bringing me fulfillment.','\n',char(10)),'Ang pagmamahal ay sagana sa aking buhay, nagbibigay sa akin ng kasiyahan.');
INSERT INTO quotes VALUES(321,'life',replace('\nMy heart is open to giving and receiving love.','\n',char(10)),'Bukas ang aking puso sa pagbibigay at pagtanggap ng pagmamahal.');
INSERT INTO quotes VALUES(322,'life','Life has no blessing like a prudent friend. ','Walang biyayang hihigit sa maingat na kaibigan.');
INSERT INTO quotes VALUES(323,'life',replace('\nBelieve in the power of genuine friendships. ','\n',char(10)),'Maniwala sa lakas ng tunay na pagkakaibigan.');
INSERT INTO quotes VALUES(324,'life',replace('\nSurround yourself with wise and caring companions. ','\n',char(10)),'Paligiran ang iyong sarili ng maingat at mapagkalingang mga kasama.');
INSERT INTO quotes VALUES(325,'life',replace('\nChoose friends who uplift and support you. ','\n',char(10)),'Piliin ang mga kaibigang nagbibigay inspirasyon at suporta sa iyo.');
INSERT INTO quotes VALUES(326,'life',replace('\nValue the gift of having loyal confidants. ','\n',char(10)),'Pahalagahan ang regalo ng pagkakaroon ng tapat na kaibigan.');
INSERT INTO quotes VALUES(327,'life','Embrace mistakes as lessons for growth and progress.','Tanggapin ang mga pagkakamali bilang aral para sa pag-unlad at progreso.');
INSERT INTO quotes VALUES(328,'life','Believe that every mistake teaches valuable lessons.','Maniwala na bawat pagkakamali ay nagtuturo ng mahahalagang aral.');
INSERT INTO quotes VALUES(329,'life','Mistakes are stepping stones to success.','Ang pagkakamali ay mga yapak patungo sa tagumpay.');
INSERT INTO quotes VALUES(330,'life','Mistakes do not define my worth or capability.','Hindi sumasalamin ang mga pagkakamali sa aking halaga o kakayahan.');
INSERT INTO quotes VALUES(331,'life','I honor my mistakes as part of my unique journey.','Pinahahalagahan ko ang mga pagkakamali bilang bahagi ng aking natatanging paglalakbay.');
INSERT INTO quotes VALUES(332,'life',replace('\nYour writing is a reflection of the intricacies of modern life.','\n',char(10)),'Ang iyong pagsusulat ay isang salamin ng mga kumplikasyon ng makabagong buhay.');
INSERT INTO quotes VALUES(333,'life',replace('\nYou weave technology seamlessly into your storytelling.','\n',char(10)),'Isinasama mo nang maganda ang teknolohiya sa iyong pagkukuwento.');
INSERT INTO quotes VALUES(334,'life',replace('\nYour narrative embraces the intersection of technology and humanity.','\n',char(10)),'Ang iyong kwento ay sumasalamin sa pagtatagpo ng teknolohiya at kahumanan.');
INSERT INTO quotes VALUES(335,'life',replace('\nYou tell stories that incorporate the essence of modern living.','\n',char(10)),'Ikaw ay nagsasalaysay ng mga kuwentong naglalaman ng esensya ng makabagong pamumuhay.');
INSERT INTO quotes VALUES(336,'life','Cherish each moment as it fuels the essence of life''s beauty. ','Pahalagahan ang bawat sandali dahil ito ang nagbibigay kulay sa ganda ng buhay.');
INSERT INTO quotes VALUES(337,'life',replace('\nEmbrace every opportunity to create a life filled with joy. ','\n',char(10)),'Sama-sama nating samantalahin ang bawat pagkakataon na bumuo ng buhay na puno ng ligaya.');
INSERT INTO quotes VALUES(338,'life',replace('\nTime spent wisely is the foundation of a fulfilled life. ','\n',char(10)),'Ang tamang paggamit ng oras ay pundasyon ng isang masaganang buhay.');
INSERT INTO quotes VALUES(339,'life',replace('\nLive fully in the present to enrich the tapestry of your life. ','\n',char(10)),'Mabuhay ng buo sa kasalukuyan upang pahusayin ang kuwento ng iyong buhay.');
INSERT INTO quotes VALUES(340,'life',replace('\nSeize each day with purpose and watch your life flourish. ','\n',char(10)),'Isakatuparan ang bawat araw nang may layunin at panoorin ang iyong buhay na umusbong.');
INSERT INTO quotes VALUES(341,'work','I embrace failures as lessons towards success. ','Ako''y tumatanggap ng mga pagkakamali bilang aral patungo sa tagumpay.');
INSERT INTO quotes VALUES(342,'work','I believe in my ability to overcome obstacles. ','Ako''y naniniwala sa aking kakayahan na lampasan ang mga hamon.');
INSERT INTO quotes VALUES(343,'work','I persistently seek solutions in every setback. ','Ako''y patuloy na naghahanap ng solusyon sa bawat pagsubok.');
INSERT INTO quotes VALUES(344,'work','Every attempt brings me closer to victory. ','Ang bawat hakbang ay nagdadala sa akin malapit sa tagumpay.');
INSERT INTO quotes VALUES(345,'work','I am resilient in the face of challenges. ','Ako''y matatag sa harap ng mga pagsubok.');
INSERT INTO quotes VALUES(346,'work','Our work showcases our strengths. ',' Ang ating trabaho ay nagpapakita ng ating kakayahan. ');
INSERT INTO quotes VALUES(347,'work',replace(' \nI am capable and talented. ','\n',char(10)),' Ako ay magaling at may kakayahan. ');
INSERT INTO quotes VALUES(348,'work',replace(' \nMy skills shine through my work. ','\n',char(10)),' Ang aking mga talento ay nagbibigay ningning sa aking trabaho. ');
INSERT INTO quotes VALUES(349,'work',replace('\nI am confident in my abilities. ','\n',char(10)),' May tiwala ako sa aking kakayahan. ');
INSERT INTO quotes VALUES(350,'work',replace('\nI take pride in my work. ','\n',char(10)),' Ako''y nagmamalaki sa aking gawa. ');
INSERT INTO quotes VALUES(351,'work','You bring new life to ideas through innovation and perseverance. ',' Binibigyan mo ng bagong sigla ang mga ideya sa pamamagitan ng imbensyon at katatagan.');
INSERT INTO quotes VALUES(352,'work','You are constantly evolving and improving.',' Ikaw ay patuloy na nagbabago at lumalago.');
INSERT INTO quotes VALUES(353,'work',replace('\nEvery setback is just a stepping stone to success.','\n',char(10)),' Ang bawat pagsubok ay isang hakbang patungo sa tagumpay.');
INSERT INTO quotes VALUES(354,'work',replace('\nYour potential for growth is limitless.','\n',char(10)),' Walang hanggang ang iyong potensyal para sa pag-unlad.');
INSERT INTO quotes VALUES(355,'work',replace('\nChallenges are opportunities in disguise.','\n',char(10)),' Ang mga hamon ay mga pagkakataon na nakatago.');
INSERT INTO quotes VALUES(356,'work',replace('\nYou have the power to turn failures into victories.','\n',char(10)),' May kakayahan kang gawing tagumpay ang mga pagkabigo.');
INSERT INTO quotes VALUES(357,'work','You find peace in productivity. ',' Natatagpuan mo ang kapayapaan sa produktibidad. ');
INSERT INTO quotes VALUES(358,'work',replace(' \nHard work eases your mind. ','\n',char(10)),' Ang masipag na pagtatrabaho ay nagpapaluwag ng iyong isipan. ');
INSERT INTO quotes VALUES(359,'work',replace(' \nYour dedication quiets your fears. ','\n',char(10)),' Ang iyong dedikasyon ay nagpapatahimik sa iyong mga takot. ');
INSERT INTO quotes VALUES(360,'work',replace(' \nWork is your remedy for anxiety. ','\n',char(10)),' Ang trabaho ay ang lunas mo sa pag-aalala. ');
INSERT INTO quotes VALUES(361,'work',replace(' \nYou replace worry with effort. ','\n',char(10)),' Pinapalitan mo ang pag-aalala ng pagsisikap. ');
INSERT INTO quotes VALUES(362,'work','Our work reflects our abilities.','Ang ating trabaho ay nagpapakita ng ating kakayahan.');
INSERT INTO quotes VALUES(363,'work',replace('\nI am capable and my work shows it.','\n',char(10)),'Ako ay magaling at ito''y ipinapakita ng aking trabaho.');
INSERT INTO quotes VALUES(364,'work',replace('\nI am skilled and my work proves it.','\n',char(10)),'May kasanayan ako at ito''y pinapatunayan ng aking trabaho.');
INSERT INTO quotes VALUES(365,'work',replace('\nMy potential shines through my work.','\n',char(10)),'Naglalabas ang aking potensyal sa pamamagitan ng aking trabaho.');
INSERT INTO quotes VALUES(366,'work',replace('\nI am competent, and my work speaks for itself.','\n',char(10)),'Mahusay ako, at nagsasalita para sa akin ang aking trabaho.');
INSERT INTO quotes VALUES(367,'work','I embrace mistakes as stepping stones to success. ','Minamahal ko ang pagkakamali bilang hakbang patungo sa tagumpay.');
INSERT INTO quotes VALUES(368,'work',replace(' \nI am resilient and grow from every setback. ','\n',char(10)),'Matibay ako at lumalaki sa bawat pagkatalo.');
INSERT INTO quotes VALUES(369,'work',replace(' \nI see challenges as opportunities to learn and improve. ','\n',char(10)),'Nakikita ko ang mga hamon bilang pagkakataon upang mag-aral at mag-improve.');
INSERT INTO quotes VALUES(370,'work',replace(' \nI am persistent and believe in my ability to find solutions. ','\n',char(10)),'Matiyaga ako at naniniwala sa aking kakayahan na makahanap ng solusyon.');
INSERT INTO quotes VALUES(371,'work',replace(' \nI trust in my journey, knowing failures are part of it. ','\n',char(10)),'Tiwala ako sa aking paglalakbay, batid na ang mga pagkabigo ay bahagi nito.');
INSERT INTO quotes VALUES(372,'work','You possess extraordinary abilities beyond any machine''s capacity. ',' Mayroon kang kahusayan na lampas sa kakayahan ng anumang makina.');
INSERT INTO quotes VALUES(373,'work',replace('\nYour unique talents are invaluable and unmatched by technology. ','\n',char(10)),' Ang iyong natatanging mga talento ay walang katulad at hindi maikukumpara sa teknolohiya.');
INSERT INTO quotes VALUES(374,'work',replace('\nYou are incomparable and irreplaceable in your exceptional skills. ','\n',char(10)),' Ikaw ay kakaiba at hindi mapapalitan sa iyong kahusayang natatangi.');
INSERT INTO quotes VALUES(375,'work',replace('\nYour greatness outshines any technological advancement. ','\n',char(10)),' Ang iyong kahusayan ay mas maganda kaysa anumang pagsulong sa teknolohiya.');
INSERT INTO quotes VALUES(376,'work',replace('\nYou are a visionary individual with immense capabilities. ','\n',char(10)),' Ikaw ay isang taong may pangarap na may napakalaking kakayahan.');
INSERT INTO quotes VALUES(377,'work','You are on the path to finding your true purpose and passion.','Ikaw ay nasa landas ng paghahanap sa tunay na layunin at pagnanais mo.');
INSERT INTO quotes VALUES(378,'work',replace('\nYou radiate success when you do what you truly love.','\n',char(10)),'Nagpaparangya ka ng tagumpay kapag ginagawa mo ang tunay na iyong iniibig.');
INSERT INTO quotes VALUES(379,'work',replace('\nYou are deserving of a fulfilling career that brings you joy.','\n',char(10)),'Ikaw ay karapat-dapat sa isang nakabubusog na karera na nagdudulot sa iyo ng ligaya.');
INSERT INTO quotes VALUES(380,'work',replace('\nYou attract abundance and success through your genuine love for your work.','\n',char(10)),'Humuhugot ka ng kasaganaan at tagumpay sa pamamagitan ng iyong tunay na pagmamahal sa iyong trabaho.');
INSERT INTO quotes VALUES(381,'work',replace('\nYour dedication to your passion will lead you to great achievements.','\n',char(10)),'Ang iyong dedikasyon sa iyong pagnanais ay magdadala sa iyo sa mga dakilang tagumpay.');
INSERT INTO quotes VALUES(382,'happy','You choose your own happiness. ','Ikaw ang nagpapasya ng iyong kaligayahan.');
INSERT INTO quotes VALUES(383,'happy',replace('\nI radiate positivity and joy. ','\n',char(10)),'Ako''y sumasabog ng positibong enerhiya at kaligayahan.');
INSERT INTO quotes VALUES(384,'happy',replace('\nMy happiness is in my hands. ','\n',char(10)),'Nasa akin ang aking kaligayahan.');
INSERT INTO quotes VALUES(385,'happy',replace('\nI attract happiness effortlessly. ','\n',char(10)),'Madaling tumanggap ng kaligayahan.');
INSERT INTO quotes VALUES(386,'happy',replace('\nI am the architect of my own joy. ','\n',char(10)),'Ako ang arkitekto ng aking kasiyahan.');
INSERT INTO quotes VALUES(387,'happy','You have the power to choose your own happiness ','May kapangyarihan ka na pumili ng iyong sariling kaligayahan');
INSERT INTO quotes VALUES(388,'happy',replace('\nYou control your own happiness ','\n',char(10)),'Ikaw ang namamahala ng iyong sariling kaligayahan');
INSERT INTO quotes VALUES(389,'happy',replace('\nChoose to be happy in every moment ','\n',char(10)),'Pumili na maging masaya sa bawat sandali');
INSERT INTO quotes VALUES(390,'happy',replace('\nYour happiness is in your hands ','\n',char(10)),'Nasa mga kamay mo ang iyong kaligayahan');
INSERT INTO quotes VALUES(391,'happy',replace('\nDecide to be joyful always ','\n',char(10)),'Pumili na maging masaya palagi');
INSERT INTO quotes VALUES(392,'happy','You have the power to create your own happiness.','May kakayahan ka na lumikha ng sarili mong kaligayahan.');
INSERT INTO quotes VALUES(393,'happy','Believe in your ability to choose joy.','Maniwala sa kakayahan mong pumili ng kasiyahan.');
INSERT INTO quotes VALUES(394,'happy','Your mindset shapes your happiness.','Ang iyong pananaw ang bumubuo sa iyong kaligayahan.');
INSERT INTO quotes VALUES(395,'happy','Choose positivity and attract happiness.','Piliin ang positibong pananaw at akitin ang kaligayahan.');
INSERT INTO quotes VALUES(396,'happy','Decide to radiate joy in every moment.','Magpasya na magbigay-liwanag ng kaligayahan sa bawat sandali.');
INSERT INTO quotes VALUES(397,'happy','You are capable of great kindness and true greatness.','Kayang-kaya mong maging mabait at tunay na dakila.');
INSERT INTO quotes VALUES(398,'happy',replace('\nYour mind is filled with wisdom and happiness.','\n',char(10)),'Ang iyong isip ay puno ng Karunungan at Kasiyahan.');
INSERT INTO quotes VALUES(399,'happy',replace('\nChoose kindness as your path to true greatness.','\n',char(10)),'Piliin ang kabaitan bilang daan sa tunay na kadakilaan.');
INSERT INTO quotes VALUES(400,'happy',replace('\nEmbrace a happy mind to unlock true wisdom within you.','\n',char(10)),'Tanggapin ang masayang isip upang lumiwanag ang tunay na karunungan sa''yo.');
INSERT INTO quotes VALUES(401,'happy',replace('\nYour kindness brings out your true greatness and wisdom.','\n',char(10)),'Ang iyong kabaitan ay nagbubukas ng tunay mong kadakilaan at karunungan.');
INSERT INTO quotes VALUES(402,'happy','Believe in your ability to embrace yourself with joy. ',' Maniwala sa kakayahan mong yakapin ang iyong sarili na may kasiyahan. ');
INSERT INTO quotes VALUES(403,'happy',replace('  \nYou are capable of feeling happiness without fear. ','\n',char(10)),' Kaya mong maramdaman ang kaligayahan nang walang takot. ');
INSERT INTO quotes VALUES(404,'happy',replace('  \nEmbrace self-awareness with confidence and peace. ','\n',char(10)),' Yakapin ang pagiging mahinahon at mapayapa sa sarili. ');
INSERT INTO quotes VALUES(405,'happy',replace('  \nFind comfort in being mindful of your own being. ','\n',char(10)),' Hanapin ang ginhawa sa pagiging mapanuri sa iyong sarili. ');
INSERT INTO quotes VALUES(406,'happy',replace('  \nCelebrate the freedom of being true to yourself. ','\n',char(10)),' Ipagdiwang ang kalayaan sa pagiging tapat sa sarili. ');
INSERT INTO quotes VALUES(407,'mind','A disciplined mind brings happiness.','Ang isang disiplinadong isip ay nagdudulot ng kaligayahan.');
INSERT INTO quotes VALUES(408,'mind',replace('\nBelieve in your ability to create positive change.','\n',char(10)),'Maniwala sa iyong kakayahan na makagawa ng positibong pagbabago.');
INSERT INTO quotes VALUES(409,'mind',replace('\nYou are capable of achieving great things.','\n',char(10)),'Kaya mong makamit ang mga magagandang bagay.');
INSERT INTO quotes VALUES(410,'mind',replace('\nLove flows to and from you abundantly.','\n',char(10)),'Ang pagmamahal ay umaagos mula sa iyo ng sagana at patungo sa iyo ng sagana.');
INSERT INTO quotes VALUES(411,'mind',replace('\nYou are deserving of love and respect.','\n',char(10)),'Ikaw ay karapat-dapat sa pagmamahal at respeto.');
INSERT INTO quotes VALUES(412,'mind','You create your own reality with the power of your mind. ',' Lumikha ka ng iyong sariling reyalidad sa pamamagitan ng kapangyarihan ng iyong isip. ');
INSERT INTO quotes VALUES(413,'mind',replace(' \nYour mind is the key to manifesting your desires. ','\n',char(10)),' Ang iyong isip ang susi sa pagpapahayag ng iyong mga naisin. ');
INSERT INTO quotes VALUES(414,'mind',replace('\nMaster your mind to master your life. ','\n',char(10)),' Pahalagahan ang iyong isip upang pamahalaan ang iyong buhay. ');
INSERT INTO quotes VALUES(415,'mind',replace('\nYour thoughts shape your world. ','\n',char(10)),' Ang iyong mga iniisip ang humuhulma sa iyong mundo. ');
INSERT INTO quotes VALUES(416,'mind',replace('\nBelieve in the power of your mind to transform your reality. ','\n',char(10)),' Maniwala sa kapangyarihan ng iyong isip na baguhin ang iyong realidad. ');
INSERT INTO quotes VALUES(417,'mind','You are a true friend, valued and cherished. ',' Ikaw ay tunay na kaibigan, pinahahalagahan at minamahal. ');
INSERT INTO quotes VALUES(418,'mind',replace(' \nTogether, we create a bond that can withstand anything. ','\n',char(10)),' Magkasama, lumilikha tayo ng ugnayan na kayang tibagin ang anuman. ');
INSERT INTO quotes VALUES(419,'mind',replace(' \nYou bring warmth and light to my life. ','\n',char(10)),' Ikaw ang nagbibigay ng init at liwanag sa aking buhay. ');
INSERT INTO quotes VALUES(420,'mind',replace(' \nOur connection is deep and unbreakable. ','\n',char(10)),' Ang ating koneksyon ay malalim at hindi mapaputol. ');
INSERT INTO quotes VALUES(421,'mind',replace(' \nIn your presence, I find comfort and understanding. ','\n',char(10)),' Sa iyong piling, natatagpuan ko ang ginhawa at pang-unawa. ');
INSERT INTO quotes VALUES(422,'mind','Mind is a powerful force driving my success and growth. ',' Ang isipan ang nagtutulak sa aking tagumpay at pag-unlad.');
INSERT INTO quotes VALUES(423,'mind',replace('\nI control my destiny with the power of my mind. ','\n',char(10)),' Ako ang naghahari sa aking kapalaran sa tulong ng aking isipan.');
INSERT INTO quotes VALUES(424,'mind',replace('\nI am capable of achieving anything with a focused mind. ','\n',char(10)),' Kaya kong makamit ang anuman sa tulong ng aking nakatuon na isipan.');
INSERT INTO quotes VALUES(425,'mind',replace('\nMy mind shapes my reality and creates endless possibilities. ','\n',char(10)),' Ang aking isipan ang bumubuo ng aking reyalidad at lumilikha ng walang hanggang mga posibilidad.');
INSERT INTO quotes VALUES(426,'mind',replace('\nI am grateful for the strength and clarity of my mind. ','\n',char(10)),' Lubos akong nagpapasalamat sa lakas at kalinawan ng aking isipan.');
INSERT INTO quotes VALUES(427,'mind','Trust your intuition in guiding your thoughts and actions.','Tiwalang sundan ang iyong intuwisyon sa paggabay ng iyong mga saloobin at kilos.');
INSERT INTO quotes VALUES(428,'mind',replace('\nLet your intuition lead you to the right path.','\n',char(10)),'Pahintulutan ang iyong intuwisyon na magdala sa iyo sa tamang daan.');
INSERT INTO quotes VALUES(429,'mind',replace('\nListen to your inner voice for direction.','\n',char(10)),'Makinig sa iyong kalooban para sa gabay.');
INSERT INTO quotes VALUES(430,'mind',replace('\nBelieve in the power of your intuition.','\n',char(10)),'Maniwala sa lakas ng iyong intuwisyon.');
INSERT INTO quotes VALUES(431,'mind',replace('\nYour intuition knows the way. Trust it.','\n',char(10)),'Alam ng iyong intuwisyon ang landas. Tiwalaan ito.');
INSERT INTO quotes VALUES(432,'mind','Always keep an open mind and a compassionate heart. ',' palaging magkaroon ng bukas na isip at mapagmahal na puso. ');
INSERT INTO quotes VALUES(433,'mind',replace(' \nBelieve in your inner strength and limitless potential. ','\n',char(10)),' maniwala sa iyong lakas at walang hanggang potensyal. ');
INSERT INTO quotes VALUES(434,'mind',replace(' \nEmbrace challenges as opportunities for growth. ','\n',char(10)),' yakapin ang mga hamon bilang pagkakataon para sa pag-unlad. ');
INSERT INTO quotes VALUES(435,'mind',replace(' \nChoose kindness over anger, love over hate. ','\n',char(10)),' piliin ang kabutihan kaysa sa galit, pag-ibig kaysa sa poot. ');
INSERT INTO quotes VALUES(436,'mind',replace(' \nCelebrate small victories and progress every day. ','\n',char(10)),' ipagdiwang ang mga maliit na tagumpay at pag-unlad araw-araw. ');
INSERT INTO quotes VALUES(437,'mind','Embrace peace to soothe your restless thoughts. ','Sundan ang kapayapaan upang pawiin ang iyong magulo na isipan.');
INSERT INTO quotes VALUES(438,'mind','Stay mindful, calmness brings a tranquil sleep. ','Manatiling mapanatag, ang kalinawan ay nagdudulot ng payapang tulog.');
INSERT INTO quotes VALUES(439,'mind','Your serene mind tucks your worries to rest. ','Ang iyong payapang isipan ay nagpapatulog sa iyong mga alalahanin.');
INSERT INTO quotes VALUES(440,'mind','Inner calmness gives you a peaceful slumber. ','Ang kalinawang nasa loob ay nagbibigay sa iyo ng payapang pagkakatulog.');
INSERT INTO quotes VALUES(441,'mind','Nurture tranquility for a well-rested mind. ','Ingatan ang kalinawan para sa isang mahimbing na pag-iisip.');
INSERT INTO quotes VALUES(442,'mind','Fears do not control me. ',' Ang takot ay hindi sumasakop sa akin.');
INSERT INTO quotes VALUES(443,'mind',replace('\nI am stronger than my fears. ','\n',char(10)),' Ako ay mas matatag kaysa sa aking mga takot.');
INSERT INTO quotes VALUES(444,'mind',replace('\nI release all fears and embrace courage. ','\n',char(10)),' Inilalabas ko ang lahat ng takot at tinatanggap ang lakas ng loob.');
INSERT INTO quotes VALUES(445,'mind',replace('\nI am in control of my thoughts and emotions. ','\n',char(10)),' Ako ang nangangasiwa ng aking mga iniisip at emosyon.');
INSERT INTO quotes VALUES(446,'mind',replace('\nMy mind is powerful and can overcome any fear. ','\n',char(10)),' Ang aking isipan ay makapangyarihan at kayang lampasan ang anumang takot.');
INSERT INTO quotes VALUES(447,'mind','You are humble and wise, embracing growth and learning. ','Ikaw ay mapagpakumbaba at marunong, tumatanggap ng pag-unlad at kaalaman.');
INSERT INTO quotes VALUES(448,'mind',replace('\nYou radiate humility and wisdom, letting go of arrogance. ','\n',char(10)),'Ikaw ay nagpapakalat ng kababaang-loob at karunungan, nagpapaalis ng kayabangan.');
INSERT INTO quotes VALUES(449,'mind',replace('\nYour mind is open and expansive, free from arrogance. ','\n',char(10)),'Ang iyong isipan ay bukas at malawak, malaya sa kayabangan.');
INSERT INTO quotes VALUES(450,'mind',replace('\nYou possess a humble heart, rejecting conceited thoughts. ','\n',char(10)),'Ikaw ay may mapagpakumbabang puso, tinatanggihan ang mga palalo at nagmamagaling na pag-iisip.');
INSERT INTO quotes VALUES(451,'mind',replace('\nYou are confident without arrogance, radiating inner beauty. ','\n',char(10)),'Ikaw ay tiwala sa sarili ngunit walang kayabangan, nagpapakalat ng kagandahan sa loob.');
INSERT INTO quotes VALUES(452,'mind','You radiate powerful energy from your mind. ',' Naglalabas ka ng matinding enerhiya mula sa iyong isipan. ');
INSERT INTO quotes VALUES(453,'mind',replace('\nYou are the essence of life''s vitality. ','\n',char(10)),' Ikaw ang essensya ng sigla ng buhay. ');
INSERT INTO quotes VALUES(454,'mind',replace('\nYour mind is a source of life''s essence. ','\n',char(10)),' Ang iyong isipan ay puno ng essensya ng buhay. ');
INSERT INTO quotes VALUES(455,'mind',replace('\nLife''s essence flows through your mind. ','\n',char(10)),' Ang essensya ng buhay ay dumadaloy sa iyong isipan. ');
INSERT INTO quotes VALUES(456,'mind',replace('\nYour mind''s energy fuels your vibrant life. ','\n',char(10)),' Ang enerhiya ng iyong isipan ang nagbibigay sigla sa iyong buhay. ');
INSERT INTO quotes VALUES(457,'mind','You are capable of achieving success through your determination.','Kayang-kaya mong magtagumpay sa pamamagitan ng iyong determinasyon.');
INSERT INTO quotes VALUES(458,'mind',replace('\nBelieve in your ability to overcome obstacles and reach your goals.','\n',char(10)),'Maniwala sa iyong kakayahan na lampasan ang mga hadlang at maabot ang iyong mga layunin.');
INSERT INTO quotes VALUES(459,'mind',replace('\nYour commitment to success is stronger than any challenge.','\n',char(10)),'Ang iyong determinasyon sa tagumpay ay mas matibay kaysa anumang hamon.');
INSERT INTO quotes VALUES(460,'mind',replace('\nYour success is a reflection of your unwavering resolve.','\n',char(10)),'Ang iyong tagumpay ay bunga ng iyong matibay na determinasyon.');
INSERT INTO quotes VALUES(461,'mind',replace('\nEach step towards your goals brings you closer to success.','\n',char(10)),'Bawat hakbang patungo sa iyong mga layunin ay nagdadala sa iyo sa tagumpay.');
INSERT INTO quotes VALUES(462,'mind','I radiate greatness through kindness.',replace('Naglalabas ako ng kadakilaan sa pamamagitan ng kabaitan.\nI hold wisdom in my joyful heart.','\n',char(10)));
INSERT INTO quotes VALUES(463,'mind','Your inner self shines through your outer appearance.','Ang tunay na pagkatao mo ay naglalarawan sa iyong panlabas na anyo.');
INSERT INTO quotes VALUES(464,'mind',replace('\nYou radiate positivity and confidence through your actions.','\n',char(10)),'Ikaw ay nagbibigay liwanag at kumpyansa sa iyong mga kilos.');
INSERT INTO quotes VALUES(465,'mind',replace('\nYour true essence is always reflected in your demeanor.','\n',char(10)),'Ang tunay mong pagkatao ay laging nasasalamin sa iyong kilos.');
INSERT INTO quotes VALUES(466,'mind',replace('\nYou are a beacon of authenticity and grace in all you do.','\n',char(10)),'Ikaw ay isang tanglaw ng katotohanan at kagandahang-asal sa lahat ng iyong ginagawa.');
INSERT INTO quotes VALUES(467,'mind',replace('\nEvery action you take reveals the beauty of your soul.','\n',char(10)),'Bawat kilos na iyong ginagawa ay nagpapakita ng kagandahan ng iyong kaluluwa.');
INSERT INTO quotes VALUES(468,'mind','Believe in your own ability to succeed above all else.','Maniwala sa sariling kakayahan na magtagumpay sa lahat.');
INSERT INTO quotes VALUES(469,'mind',replace('\nYou hold the key to your success.','\n',char(10)),'Ikaw ang may hawak ng susi sa iyong tagumpay.');
INSERT INTO quotes VALUES(470,'mind',replace('\nStay determined in achieving your goals.','\n',char(10)),'Maging determinado sa pag-abot ng iyong mga layunin.');
INSERT INTO quotes VALUES(471,'mind',replace('\nYour dedication is the fuel for your success.','\n',char(10)),'Ang iyong dedikasyon ang nagpapalakas sa iyong tagumpay.');
INSERT INTO quotes VALUES(472,'mind',replace('\nYour conviction to succeed drives your journey.','\n',char(10)),'Ang iyong tiwala sa sarili ang nagtutulak sa iyong paglalakbay patungo sa tagumpay.');
INSERT INTO quotes VALUES(473,'mind','You have the power to create a new path of your choosing.','Mayroon kang kapangyarihan na lumikha ng bagong landas ayon sa iyong nais.');
INSERT INTO quotes VALUES(474,'mind','You can rewrite your story at any moment.','Maaari mong baguhin ang iyong istorya sa anumang sandali.');
INSERT INTO quotes VALUES(475,'mind','Embrace the freedom to transform your life''s direction.','Tanggapin ang kalayaan na baguhin ang direksyon ng iyong buhay.');
INSERT INTO quotes VALUES(476,'mind','You possess the ability to redefine your journey.','May kakayahan kang baguhin ang iyong paglalakbay.');
INSERT INTO quotes VALUES(477,'mind','Strive towards a future that resonates with your heart.','Magsumikap tungo sa isang hinaharap na tugma sa iyong puso.');
INSERT INTO quotes VALUES(478,'mind','You have a kind heart that radiates compassion to all.','Mayroon kang mabuting puso na nagpapakita ng habag sa lahat.');
INSERT INTO quotes VALUES(479,'mind',replace('\nYou attract positivity and merit with your compassionate actions.','\n',char(10)),'Ikaw ay bumabalot ng kabutihan at merito sa iyong mga mapagmahal na kilos.');
INSERT INTO quotes VALUES(480,'mind',replace('\nYour noble deeds bring blessings to all living beings.','\n',char(10)),'Ang iyong mga mabuting gawain ay nagdudulot ng mga pagpapala sa lahat ng nilalang.');
INSERT INTO quotes VALUES(481,'mind',replace('\nCompassion flows through you, creating a harmonious environment.','\n',char(10)),'Ang habag ay dumadaloy sa iyo, lumilikha ng maayos na kapaligiran.');
INSERT INTO quotes VALUES(482,'mind',replace('\nYour kindness towards others brings you endless merits.','\n',char(10)),'Ang iyong kabaitan sa iba ay nagdadala sa iyo ng walang katapusang merito.');
INSERT INTO quotes VALUES(483,'mind','Trust your own judgment and see others through your own eyes. ','Tiwalain ang sarili mong pagpapasya at tingnan ang iba sa pamamagitan ng iyong mga mata.');
INSERT INTO quotes VALUES(484,'mind',replace('\nBelieve in your ability to form your own opinions. ','\n',char(10)),'Maniwala sa iyong kakayahan na bumuo ng sariling opinyon.');
INSERT INTO quotes VALUES(485,'mind',replace('\nStay confident in your independent assessment of others. ','\n',char(10)),'Manatiling tiwala sa iyong independiyenteng pagtataya sa iba.');
INSERT INTO quotes VALUES(486,'mind',replace('\nShine light on your unique perspective and understanding. ','\n',char(10)),'Ilantad ang liwanag sa iyong natatanging pananaw at pang-unawa.');
INSERT INTO quotes VALUES(487,'mind',replace('\nEmbrace your personal judgment and discernment. ','\n',char(10)),'Sang-ayon sa iyong personal na paghuhusga at pang-unawa.');
INSERT INTO quotes VALUES(488,'mind','You have the power to create your own path.','May kakayahan ka na bumuo ng sarili mong landas.');
INSERT INTO quotes VALUES(489,'mind',replace('\nYour choices shape your destiny.','\n',char(10)),'Ang iyong mga desisyon ay bumubuo ng iyong kapalaran.');
INSERT INTO quotes VALUES(490,'mind',replace('\nEmbrace the flexibility of your journey.','\n',char(10)),'Tanggapin ang pagiging malikhain ng iyong paglalakbay.');
INSERT INTO quotes VALUES(491,'mind',replace('\nYour past does not define your future.','\n',char(10)),'Hindi tatak ng nakaraan mo ang kinabukasan mo.');
INSERT INTO quotes VALUES(492,'mind',replace('\nYou are in control of your own narrative.','\n',char(10)),'Nasa iyo ang hawak sa iyong sariling kuwento.');
INSERT INTO quotes VALUES(493,'mind','I radiate positivity and kindness towards all. ',' Ako ay nagpapakalat ng kabutihan at kabaitan sa lahat. ');
INSERT INTO quotes VALUES(494,'mind',replace(' \nI am a source of goodness and compassion. ','\n',char(10)),' Ako ay isang tagapagdala ng kabutihan at habag. ');
INSERT INTO quotes VALUES(495,'mind',replace('\nMy heart overflows with love and generosity. ','\n',char(10)),' Ang aking puso ay puno ng pag-ibig at kabutihan. ');
INSERT INTO quotes VALUES(496,'mind',replace('\nI am deserving of love and kindness. ','\n',char(10)),' Ako ay karapat-dapat sa pagmamahal at kabaitan. ');
INSERT INTO quotes VALUES(497,'mind',replace('\nI sow seeds of kindness and empathy. ','\n',char(10)),' Ako ay nagtatanim ng mga butil ng kabaitan at pagmamalasakit. ');
INSERT INTO quotes VALUES(498,'love','You attract love effortlessly.','Nahuhumaling ka sa pag-ibig nang walang pagsisisi.');
INSERT INTO quotes VALUES(499,'love',replace('\nLove lifts you up gracefully.','\n',char(10)),'Ang pag-ibig ang nagtataas sa iyo nang maganda.');
INSERT INTO quotes VALUES(500,'love',replace('\nYou embrace the force of love.','\n',char(10)),'Tumatanggap ka ng lakas ng pag-ibig.');
INSERT INTO quotes VALUES(501,'love',replace('\nLove is a natural pull towards happiness.','\n',char(10)),'Ang pag-ibig ay likas na pagtutulak patungo sa kaligayahan.');
INSERT INTO quotes VALUES(502,'love',replace('\nYou fall in love freely and fearlessly.','\n',char(10)),'Bumabalik ka sa pag-ibig nang malaya at walang takot.');
INSERT INTO quotes VALUES(503,'life','True friends multiply joy & divide sorrows. Treasure them always!',replace('\nAng tunay na mga kaibigan ay nagpaparami ng kasiyahan at nagbabawas ng lungkot. Ingatan sila palagi!','\n',char(10)));
INSERT INTO quotes VALUES(504,'life',replace('\nStrive to have friends for a fulfilling life!','\n',char(10)),replace('\nMagsumikap na magkaroon ng mga kaibigan para sa isang masaya at makabuluhang buhay!','\n',char(10)));
INSERT INTO quotes VALUES(505,'life',replace('\nFinding a true friend is good fortune; keeping them is a blessing.','\n',char(10)),replace('\nAng matagpuan ang tunay na kaibigan ay swerte; ang panatilihin sila ay isang biyaya!','\n',char(10)));
INSERT INTO quotes VALUES(506,'life','You adapt gracefully to life''s unexpected turns. ',replace(' Marunong kang mag-adjust sa mga hindi inaasahang pangyayari.\n','\n',char(10)));
INSERT INTO quotes VALUES(507,'life',replace('\nYou embrace the spontaneity and beauty of life. ','\n',char(10)),replace(' Tinatanggap mo ng buong puso ang kagandahan ng buhay.\n','\n',char(10)));
INSERT INTO quotes VALUES(508,'life',replace('\nEvery unplanned moment is a chance for growth. ','\n',char(10)),replace(' Bawat hindi inaasahang pangyayari ay pagkakataon sa pag-unlad.\n','\n',char(10)));
INSERT INTO quotes VALUES(509,'life',replace('\nYou trust in the journey even without a clear path. ','\n',char(10)),replace(' Nagtitiwala ka sa paglalakbay kahit walang tiyak na direksyon.\n','\n',char(10)));
INSERT INTO quotes VALUES(510,'life',replace('\nYou find joy and purpose in life''s surprises. ','\n',char(10)),' Natatagpuan mo ang kasiyahan at layunin sa mga sorpresa ng buhay.');
INSERT INTO quotes VALUES(511,'life','You radiate love and attract abundance. ',' Iniindot mo ang pag-ibig at nag-aakit ng kasaganaan.');
INSERT INTO quotes VALUES(512,'life','Life is full of love and abundance. ',' Ang buhay ay puno ng pag-ibig at kasaganaan.');
INSERT INTO quotes VALUES(513,'life','You bloom with love and bear fruit abundantly. ',' Sumisibol ka ng pag-ibig at nagbubunga nang sagana.');
INSERT INTO quotes VALUES(514,'life','Your life is filled with blossoms and fruits of love. ',' Ang iyong buhay ay puno ng mga bulaklak at prutas ng pag-ibig. ');
INSERT INTO quotes VALUES(515,'life','Love enriches your life and fills it with beauty. ',' Ang pag-ibig ay nagpapayaman sa iyong buhay at nagpupuno ng kagandahan. ');
INSERT INTO quotes VALUES(516,'life','Embrace the flow of life''s energy within me!','Tanggapin ang daloy ng enerhiya ng buhay sa loob ko!');
INSERT INTO quotes VALUES(517,'life',replace('\nMy body is in sync with the rhythm of the universe!','\n',char(10)),'Ang aking katawan ay kasabay ng ritmo ng sansinukob!');
INSERT INTO quotes VALUES(518,'life',replace('\nEvery breath I take fills me with vitality and strength!','\n',char(10)),'Ang bawat hininga na aking tinatanggap ay nagbibigay sa akin ng lakas at sigla!');
INSERT INTO quotes VALUES(519,'life',replace('\nI am grateful for the ability to move and live fully!','\n',char(10)),'Ako''y nagpapasalamat sa kakayahan na gumalaw at mabuhay ng buo!');
INSERT INTO quotes VALUES(520,'life',replace('\nI honor the innate power of my body to thrive and flourish!','\n',char(10)),'Kinikilala ko ang likas na lakas ng aking katawan na umunlad at mamunga!');
INSERT INTO quotes VALUES(521,'life','Our happiness does not depend on material possessions.','Ang ating kaligayahan ay hindi nakasalalay sa mga bagay-material.');
INSERT INTO quotes VALUES(522,'life',replace('\nWe find joy in simplicity and gratitude.','\n',char(10)),'Natutuklasan natin ang kagalakan sa kababaan at pasasalamat.');
INSERT INTO quotes VALUES(523,'life',replace('\nTrue fulfillment comes from within, not from external things.','\n',char(10)),'Ang tunay na kasiyahan ay nagmumula sa loob, hindi sa labas.');
INSERT INTO quotes VALUES(524,'life',replace('\nOur worth is not defined by our possessions or achievements.','\n',char(10)),'Hindi nasusukat ang halaga natin sa ating mga ari-arian o tagumpay.');
INSERT INTO quotes VALUES(525,'life',replace('\nWe can experience true contentment by focusing on inner peace.','\n',char(10)),'Maaari nating maranasan ang tunay na kasayahan sa pamamagitan ng pagtuon sa inner peace.');
INSERT INTO quotes VALUES(526,'life',replace('\nBegin your journey to a new life now. Be fearless and go all in!','\n',char(10)),'Simulan ang paglalakbay tungo sa bagong buhay ngayon. Maging matapang at maglaan ng lahat ng puso!');
INSERT INTO quotes VALUES(527,'life','You find joy in everyday moments. ',' Natatagpuan mo ang ligaya sa pang-araw-araw na mga sandali. ');
INSERT INTO quotes VALUES(528,'life',replace(' \nEmbrace the beauty that surrounds you. ','\n',char(10)),' Yakapin ang kagandahan na bumabalot sa iyo. ');
INSERT INTO quotes VALUES(529,'life',replace(' \nLive in gratitude and positivity. ','\n',char(10)),' Mabuhay nang may pasasalamat at positibismo. ');
INSERT INTO quotes VALUES(530,'life',replace(' \nYou radiate love and light. ','\n',char(10)),' Lumalabas ang pagmamahal at liwanag sa iyo. ');
INSERT INTO quotes VALUES(531,'life',replace(' \nEmbrace life with open arms. ','\n',char(10)),' Yakapin ang buhay nang buong puso. ');
INSERT INTO quotes VALUES(532,'life','You are constantly expanding your personal truths beyond yourself. ',' Palagi kang lumalawak ng iyong personal na katotohanan sa labas ng iyong sarili.');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('quotes',532);
COMMIT;
